import { test, expect } from '@playwright/test';
import { defaultInterior } from '../../src/lib/drawers';
import { DEFAULT_CONFIG } from '../../src/lib/design';
import { roomShell } from '../../src/lib/roomShells';
import { EMPTY_INVENTORY } from '../../src/lib/inventoryPlanning';
test('shell import previews collisions and keeps independently named copies',async({page})=>{
 const shell={id:'existing',name:'Bedroom',shell:roomShell(DEFAULT_CONFIG)};await page.addInitScript(v=>localStorage.setItem('alveo-room-shells',JSON.stringify({version:1,shells:[v]})),shell);await page.goto('/configure');await page.locator('summary').filter({hasText:'Room openings, wall preferences, and sizing assumptions'}).click();await page.locator('summary').filter({hasText:'Reusable room shells'}).click();await page.getByLabel('Import room shells').setInputFiles({name:'shells.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify({version:1,shells:[shell]}))});await expect(page.getByText(/conflict: keep as an independent copy/)).toBeVisible();await page.getByRole('button',{name:'Import selected room shells'}).click();await expect.poll(()=>page.evaluate(()=>JSON.parse(localStorage.getItem('alveo-room-shells')!).shells.length)).toBe(2);const values=await page.evaluate(()=>JSON.parse(localStorage.getItem('alveo-room-shells')!).shells);expect(new Set(values.map((v:any)=>v.id)).size).toBe(2);await page.getByRole('combobox',{name:'Manage room shell',exact:true}).selectOption('existing');await page.getByLabel('Room shell name',{exact:true}).fill('Guest suite');await page.getByRole('button',{name:'Duplicate room shell'}).click();await page.getByLabel('Search room shells').fill('Guest');await expect(page.getByRole('combobox',{name:'Manage room shell',exact:true})).toContainText('Guest suite');await expect(page.getByRole('combobox',{name:'Manage room shell',exact:true})).not.toContainText('Bedroom');
});
test('household imports preserve notes by default and apply only the selected season',async({page})=>{
 const inventory=(shirts:number)=>({...structuredClone(EMPTY_INVENTORY),wardrobe:{...EMPTY_INVENTORY.wardrobe,shirts}}),household={members:[{id:'a',name:'Everyday',season:'everyday',inventory:inventory(7)},{id:'b',name:'Winter',season:'seasonal',inventory:inventory(13)}],notes:{long:'Imported note'}};await page.goto('/configure');await page.locator('summary').filter({hasText:'Household, seasonal inventory, and reserve capacity'}).click();await page.getByLabel('Import household profiles').setInputFiles({name:'household.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify({version:1,household}))});await page.getByRole('button',{name:'Confirm household import'}).click();await page.getByRole('button',{name:'Apply seasonal inventory'}).click();await expect.poll(()=>page.evaluate(()=>JSON.parse(localStorage.getItem('alveo-draft')??'null')?.config?.wardrobe?.shirts)).toBe(13);expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('alveo-draft')!).config.inventoryPlanning.notes?.long)).toBeUndefined();await page.getByLabel('Include Winter in combined inventory').uncheck();await page.getByRole('button',{name:'Apply combined household inventory'}).click();await expect.poll(()=>page.evaluate(()=>JSON.parse(localStorage.getItem('alveo-draft')??'null')?.config?.wardrobe?.shirts)).toBe(7);
});
test('template replacement history restores a separate copy and bulk deletion uses a preview',async({page})=>{
 await page.goto('/configure');await page.locator('[data-drawer-id]').first().click();const d=page.getByRole('dialog',{name:'Design drawer compartments'});await d.locator('summary').filter({hasText:'Measurements, item fit, divider tools, and custom templates'}).click();await d.getByLabel('Template name',{exact:true}).fill('Original tray');await d.getByRole('button',{name:'Save custom template'}).click();await d.getByLabel('Manage saved template').selectOption({index:1});await d.getByRole('button',{name:'Create grid',exact:true}).click();await d.getByRole('button',{name:'Preview template replacement'}).click();await d.getByRole('button',{name:'Confirm template replacement'}).click();await d.getByLabel('Previous template version').selectOption({index:1});await d.getByRole('button',{name:'Restore template version as copy'}).click();await expect.poll(()=>page.evaluate(()=>JSON.parse(localStorage.getItem('alveo-organizer-templates')!).templates.length)).toBe(2);const entries=await page.evaluate(()=>JSON.parse(localStorage.getItem('alveo-organizer-templates')!).templates);expect(entries[0].plan.cells).toHaveLength(4);expect(entries[1].plan.cells).toHaveLength(1);await d.getByLabel('Export template Original tray',{exact:true}).check();await d.getByRole('button',{name:'Preview deleting selected templates'}).click();await expect(d.getByRole('heading',{name:'Template deletion preview'})).toBeVisible();await d.getByRole('button',{name:'Delete previewed templates'}).click();await expect.poll(()=>page.evaluate(()=>JSON.parse(localStorage.getItem('alveo-organizer-templates')!).templates.length)).toBe(1);await expect(d.getByLabel('Manage saved template')).toContainText('Original tray (restored)');
});
test('room depth undo, floor-offset preview and out-of-room marker focus work',async({page})=>{
 await page.goto('/configure?preset=4');await page.locator('summary').filter({hasText:'Room openings, wall preferences, and sizing assumptions'}).click();const depth=page.getByLabel('LEFT WALL cabinet depth',{exact:true}),original=await depth.inputValue();await depth.fill('18');await depth.press('Tab');await page.getByRole('button',{name:'Apply cabinet depth'}).click();await page.getByRole('button',{name:'Undo cabinet depth change'}).click();await expect(depth).toHaveValue(original);const floor=page.getByLabel('LEFT WALL floor offset',{exact:true});await floor.fill('4');await floor.press('Tab');await expect(page.getByRole('heading',{name:'Floor offset preview'})).toBeVisible();await page.getByRole('button',{name:'Apply floor offset'}).click();await page.getByRole('button',{name:'Add obstacle',exact:true}).click();await page.getByLabel('Obstacle 1 x',{exact:true}).fill('600');await page.getByLabel('Obstacle 1 x',{exact:true}).press('Tab');await page.getByRole('button',{name:'Show floor plan'}).click();await page.getByRole('button',{name:'Review out-of-room obstacle Column',exact:true}).click();await expect(page.getByLabel('Obstacle 1 label')).toBeFocused();
});

test('template imports treat prototype-like IDs as plain identifiers',async({page})=>{
 await page.goto('/configure');await page.locator('[data-drawer-id]').first().click();const d=page.getByRole('dialog',{name:'Design drawer compartments'});await d.locator('summary').filter({hasText:'Measurements, item fit, divider tools, and custom templates'}).click();const plan=defaultInterior({width:24,depth:18,height:6,position:3,purpose:'folded'});plan.name='Imported tray';await d.getByLabel('Import organizer templates').setInputFiles({name:'templates.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify({version:1,templates:[{id:'__proto__',plan}]}))});await expect(d.getByLabel('Imported name for Imported tray')).toHaveValue('Imported tray');await d.getByRole('button',{name:'Confirm template import'}).click();await expect(d.getByLabel('Manage saved template')).toContainText('Imported tray');
});

test('retrying a failed template deletion retains its undo action',async({page})=>{
 const plan=defaultInterior({width:24,depth:18,height:6,position:3,purpose:'folded'});plan.name='Undo after retry';await page.addInitScript(plan=>localStorage.setItem('alveo-organizer-templates',JSON.stringify({version:1,templates:[{id:'t',plan}]})),plan);await page.goto('/configure');await page.locator('[data-drawer-id]').first().click();const d=page.getByRole('dialog',{name:'Design drawer compartments'});await d.locator('summary').filter({hasText:'Measurements, item fit, divider tools, and custom templates'}).click();await d.getByLabel('Manage saved template').selectOption('t');await page.evaluate(()=>{(window as any).originalSet=Storage.prototype.setItem;Storage.prototype.setItem=function(k,v){if(k==='alveo-organizer-templates')throw new DOMException('full','QuotaExceededError');return (window as any).originalSet.call(this,k,v);};});await d.getByRole('button',{name:'Delete selected template'}).click();await expect(d.getByRole('button',{name:'Retry failed template change'})).toBeVisible();await page.evaluate(()=>Storage.prototype.setItem=(window as any).originalSet);await d.getByRole('button',{name:'Retry failed template change'}).click();await d.getByRole('button',{name:'Undo template deletion'}).click();await expect(d.getByLabel('Manage saved template')).toContainText('Undo after retry');
});
