import { test, expect, type Page } from '@playwright/test';
import { ClosetLayoutEngine } from '../../src/engine/ClosetLayoutEngine';
import { defaultInterior, drawerTargets, grid } from '../../src/lib/drawers';
import { DEFAULT_CONFIG } from '../../src/lib/design';
import { EMPTY_INVENTORY } from '../../src/lib/inventoryPlanning';
const shells=async(page:Page)=>{await page.goto('/configure?preset=4');await page.locator('summary').filter({hasText:'Room openings, wall preferences, and sizing assumptions'}).click();await page.locator('summary').filter({hasText:'Reusable room shells'}).click();};
const drawer=async(page:Page)=>{await page.goto('/configure');await page.locator('[data-drawer-id]').first().click();const d=page.getByRole('dialog',{name:'Design drawer compartments'});await d.locator('summary').filter({hasText:'Measurements, item fit, divider tools, and custom templates'}).click();return d;};
test('room shell writes from two tabs preserve both records, refresh, rename, delete and undo',async({page,context})=>{
 await shells(page);const other=await context.newPage();await shells(other);await page.getByLabel('Room shell name',{exact:true}).fill('Room A');await other.getByLabel('Room shell name',{exact:true}).fill('Room B');await Promise.all([page.getByRole('button',{name:'Save room shell',exact:true}).click(),other.getByRole('button',{name:'Save room shell',exact:true}).click()]);await expect(page.getByRole('combobox',{name:'Manage room shell',exact:true})).toContainText('Room B');await expect(other.getByRole('combobox',{name:'Manage room shell',exact:true})).toContainText('Room A');await page.getByRole('combobox',{name:'Manage room shell',exact:true}).selectOption({label:'Room A'});await page.getByLabel('Room shell name',{exact:true}).fill('Room renamed');await page.getByRole('button',{name:'Rename room shell',exact:true}).click();await expect(other.getByRole('combobox',{name:'Manage room shell',exact:true})).toContainText('Room renamed');await page.getByRole('button',{name:'Delete room shell',exact:true}).click();await page.getByRole('button',{name:'Undo shell deletion'}).click();await expect(page.getByRole('combobox',{name:'Manage room shell',exact:true})).toContainText('Room renamed');
 await page.getByRole('button',{name:'Add obstacle',exact:true}).click();await page.getByLabel('Compare saved room shell').selectOption({label:'Room renamed'});await page.getByRole('button',{name:'Apply compared room shell'}).click();await expect(page.getByLabel('Obstacle 1 label')).toHaveCount(0);await page.getByRole('button',{name:'Undo applied room shell'}).click();await expect(page.getByLabel('Obstacle 1 label')).toBeVisible();
});
test('failed room-shell and template writes preserve stored bytes and retry succeeds',async({page})=>{
 await shells(page);await page.getByLabel('Room shell name',{exact:true}).fill('Retained');await page.getByRole('button',{name:'Save room shell',exact:true}).click();await expect(page.getByText('Room shell saved.',{exact:true})).toBeVisible();const before=await page.evaluate(()=>localStorage.getItem('alveo-room-shells'));await page.evaluate(()=>{(window as any).originalSet=Storage.prototype.setItem;Storage.prototype.setItem=function(k,v){if(k==='alveo-room-shells'||k==='alveo-organizer-templates')throw new DOMException('Injected full storage','QuotaExceededError');return (window as any).originalSet.call(this,k,v);};});await page.getByLabel('Room shell name',{exact:true}).fill('Failed');await page.getByRole('button',{name:'Save room shell',exact:true}).click();await expect(page.getByText('Injected full storage',{exact:true})).toBeVisible();expect(await page.evaluate(()=>localStorage.getItem('alveo-room-shells'))).toBe(before);
 await page.getByRole('button',{name:/EL-B · LEFT WALL/}).click();await page.locator('[data-drawer-id]').first().click();const d=page.getByRole('dialog',{name:'Design drawer compartments'});await d.locator('summary').filter({hasText:'Measurements, item fit, divider tools, and custom templates'}).click();await d.getByLabel('Template name',{exact:true}).fill('Retry plan');await d.getByRole('button',{name:'Save custom template'}).click();await expect(d.getByRole('button',{name:'Retry failed template change'})).toBeVisible();expect(await page.evaluate(()=>localStorage.getItem('alveo-organizer-templates'))).toBeNull();await page.evaluate(()=>Storage.prototype.setItem=(window as any).originalSet);await d.getByRole('button',{name:'Retry failed template change'}).click();await expect(d.getByLabel('Manage saved template')).toContainText('Retry plan');
});
for(const viewport of [{width:390,height:844},{width:844,height:390}])test(`expanded household and target controls fit ${viewport.width} by ${viewport.height}`,async({page})=>{
 await page.setViewportSize(viewport);await page.goto('/configure');await page.locator('summary').filter({hasText:'Household, seasonal inventory, and reserve capacity'}).click();const long='衣類・Garderobe・Vêtements '.repeat(3);await page.getByLabel('Household member name').fill(long);await page.getByRole('button',{name:'Assign entered inventory to member'}).click();await page.locator('summary').filter({hasText:'Current and target inventory'}).click();await page.getByRole('button',{name:'Capture current as target'}).click();await page.getByLabel('Target Shirts & blouses',{exact:true}).fill('57');await page.getByRole('button',{name:'Apply target counts'}).click();await page.getByRole('button',{name:'Confirm target inventory'}).click();await page.getByRole('button',{name:'Undo target inventory'}).click();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);await page.getByRole('button',{name:'Remove inventory profile'}).click();await page.getByRole('button',{name:'Undo profile removal'}).click();await expect(page.getByLabel('Edit inventory profile')).toContainText(long);
});
test('precise sizing, selective paste, rotation preview and compartment search work',async({page})=>{
 const d=await drawer(page);await d.getByRole('button',{name:'Create grid',exact:true}).click();await d.getByLabel('Merge with adjacent compartment').selectOption({index:1});await d.locator('summary').filter({hasText:'Precise compartment sizing'}).click();await d.getByLabel('Requested usable width (in)').fill('6');await d.getByRole('button',{name:'Preview compartment width'}).click();await expect(d.getByRole('heading',{name:'Shared divider change preview'})).toBeVisible();await d.getByRole('button',{name:'Apply shared divider change'}).click();await d.getByRole('button',{name:'Rotate arrangement',exact:true}).click();await expect(d.getByRole('heading',{name:'Rotation preview'})).toBeVisible();await d.getByRole('button',{name:'Confirm arrangement rotation'}).click();await d.getByLabel('Compartment label',{exact:true}).fill('Find watches');await d.getByLabel('Search compartments').fill('Find watches');await d.getByRole('button',{name:'Focus Find watches'}).click();await expect(d.getByRole('button',{name:/^Compartment 1:/})).toBeFocused();await d.getByRole('button',{name:'Copy selected cell details'}).click();await d.locator('summary').filter({hasText:'Change multiple compartments'}).click();await d.getByLabel('Select compartment 2:',{exact:false}).check();await d.getByRole('button',{name:'Preview paste to selected cells'}).click();await d.getByLabel('Paste label',{exact:true}).uncheck();await d.getByRole('button',{name:'Confirm cell detail paste'}).click();await d.getByRole('button',{name:'Clear compartment selection'}).click();await expect(d.getByText(/0 selected compartments; 0 items/)).toBeVisible();
});
test('long household print repeats headers and named presets reset safely',async({page})=>{
 const config={...DEFAULT_CONFIG,inventoryPlanning:{members:Array.from({length:10},(_,i)=>({id:String(i),name:`衣類・Vêtements ${i} `+'Long profile '.repeat(4),season:'everyday',inventory:EMPTY_INVENTORY})),notes:{long:'Measured coat '.repeat(30)}}};await page.addInitScript(c=>localStorage.setItem('alveo-draft',JSON.stringify({version:1,config:c})),config);await page.goto('/configure');await page.getByRole('button',{name:'Export',exact:true}).click();await page.getByRole('menuitem',{name:'Print options and preview'}).click();const d=page.getByRole('dialog',{name:'Print options and preview'});await d.getByLabel('Include household and season totals').check();await d.getByLabel('Include reserve percentages and inventory notes').check();await d.locator('summary').filter({hasText:'Named print presets'}).click();await d.getByRole('textbox',{name:'Print preset name',exact:true}).fill('Installation review');await d.getByRole('button',{name:'Save print preset'}).click();await d.getByRole('textbox',{name:'New print preset name',exact:true}).fill('Renamed review');await d.getByRole('button',{name:'Rename print preset'}).click();await expect(d.getByRole('textbox',{name:'Print preset name',exact:true})).toHaveValue('Renamed review');await d.getByRole('button',{name:'Reset print preferences'}).click();await expect(d.getByLabel('Include household and season totals')).not.toBeChecked();await d.getByRole('button',{name:'Load print preset'}).click();await expect(d.getByLabel('Include household and season totals')).toBeChecked();await d.getByRole('button',{name:'Preview page breaks'}).click();const frame=d.frameLocator('iframe');await expect(frame.locator('.preview-page').first()).toBeVisible();expect(await frame.locator('thead').filter({hasText:'Profile'}).count()).toBeGreaterThan(1);expect(await frame.locator('tbody tr').filter({hasText:'Season total'}).count()).toBeGreaterThan(10);await expect(frame.getByRole('heading',{name:'Reserve percentages and inventory notes'})).toBeVisible();
});
test('recovery report distinguishes unreadable draft and allows reviewed replacement',async({page})=>{
 await page.addInitScript(()=>localStorage.setItem('alveo-draft','{"version":1,"config":{}}'));await page.goto('/configure');await page.locator('summary').filter({hasText:'Device storage & recovery'}).click();await page.locator('summary').filter({hasText:'Storage usage and recovery report'}).click();await page.getByRole('button',{name:'Show selectable diagnostic report'}).click();await expect(page.getByLabel('Selectable recovery report')).toContainText('"restorable": false');const download=page.waitForEvent('download');await page.getByRole('button',{name:'Download unreadable draft before replacement'}).click();await download;await page.getByRole('button',{name:'Preview unreadable draft replacement'}).click();await page.getByRole('button',{name:'Replace reviewed unreadable draft'}).click();expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('alveo-draft')!).config.dimensions.width)).toBeGreaterThan(0);
});

test('long translated names remain usable in library and template dialogs',async({page})=>{
 const name='衣類・Garderobe・Vêtements '.repeat(3);await page.setViewportSize({width:390,height:844});const d=await drawer(page);await d.getByLabel('Template name',{exact:true}).fill(name);await d.getByRole('button',{name:'Save custom template'}).click();await d.getByLabel('Manage saved template').selectOption({label:name});await d.getByLabel('Template tags').fill('衣類, vêtements, garderobe');await d.getByRole('button',{name:'Save template tags'}).click();expect(await d.evaluate(el=>el.scrollWidth<=el.clientWidth+1)).toBe(true);await d.getByRole('button',{name:'Close editor'}).click();await page.getByRole('button',{name:'Save',exact:true}).click();await page.evaluate(name=>{const raw=JSON.parse(localStorage.getItem('alveo-saved-designs')!);raw.designs[0].name=name;localStorage.setItem('alveo-saved-designs',JSON.stringify(raw));},name);await page.reload();await page.getByRole('button',{name:/Manage saved designs/}).click();const library=page.getByRole('dialog',{name:'Saved designs'});await expect(library.getByText(name,{exact:true})).toBeVisible();expect(await library.evaluate(el=>el.scrollWidth<=el.clientWidth+1)).toBe(true);
});
test('a long compartment schedule paginates every row and repeats its header',async({page})=>{
 const config=structuredClone(DEFAULT_CONFIG),target=drawerTargets(new ClosetLayoutEngine(config).calculateLayout())[0],plan=defaultInterior(target.drawer);plan.identity=target.identity;plan.name='Long compartment schedule';plan.cells=grid(6,6).map((c,i)=>({...c,label:`Compartment ${i+1}`,notes:'Long measurement note '.repeat(13)}));config.drawerInteriors={[target.id]:plan};await page.addInitScript(c=>localStorage.setItem('alveo-draft',JSON.stringify({version:1,config:c})),config);await page.goto('/configure');await page.getByRole('button',{name:'Export',exact:true}).click();await page.getByRole('menuitem',{name:'Print options and preview'}).click();const d=page.getByRole('dialog',{name:'Print options and preview'});await d.getByRole('button',{name:'Preview page breaks'}).click();const frame=d.frameLocator('iframe');await expect(frame.locator('.preview-page').first()).toBeVisible();await expect(frame.locator('tbody tr').filter({hasText:'Long measurement note'})).toHaveCount(36);expect(await frame.locator('thead').filter({hasText:'Planned items'}).count()).toBeGreaterThan(1);
});

test('folder metadata previews and favorite order persist',async({page})=>{
 await page.goto('/configure');await page.getByRole('button',{name:'Save',exact:true}).click();await page.getByRole('button',{name:'Save',exact:true}).click();await page.getByRole('button',{name:/Manage saved designs/}).click();const d=page.getByRole('dialog',{name:'Saved designs'});await d.getByRole('button',{name:'Select visible'}).click();await d.locator('summary').filter({hasText:'Project folders, revisions, and cleanup'}).click();await d.getByLabel('Destination project folder').fill('Old folder');await d.getByRole('button',{name:'Move selected to folder'}).click();await d.getByLabel('Source project folder').selectOption('Old folder');await d.getByLabel('Destination project folder').fill('New folder');await d.getByRole('button',{name:'Preview folder rename or merge'}).click();await expect(d.getByRole('heading',{name:'Library metadata change preview'})).toBeVisible();await d.getByRole('button',{name:'Apply previewed metadata changes'}).click();await d.getByLabel('Bulk project tags').fill('Surveyed, Ready');await d.getByRole('button',{name:'Preview bulk tag change'}).click();await d.getByRole('button',{name:'Apply previewed metadata changes'}).click();await expect.poll(()=>page.evaluate(()=>JSON.parse(localStorage.getItem('alveo-saved-designs')!).designs.every((v:any)=>v.folder==='New folder'&&v.tags.includes('Surveyed')))).toBe(true);await d.getByRole('button',{name:'Pin favorite',exact:true}).first().click();await d.getByRole('button',{name:'Pin favorite',exact:true}).click();const beforeOrder=await page.evaluate(()=>JSON.parse(localStorage.getItem('alveo-saved-designs')!).designs.map((v:any)=>v.pinnedOrder));await d.getByRole('button',{name:'Move favorite down'}).first().click();await expect.poll(()=>page.evaluate(()=>JSON.parse(localStorage.getItem('alveo-saved-designs')!).designs.map((v:any)=>v.pinnedOrder))).toEqual(beforeOrder.map((v:number)=>1-v));
});

test('centimetre ruler and floor-plan view state are independent of elevations', async ({ page }) => {
  await page.goto('/configure?preset=4');
  const visibleCanvas = page.getByRole('region', { name: 'Drawing canvas. Use zoom controls and scroll to pan.' });
  const controls = () => visibleCanvas.locator('..');
  await page.getByLabel('Show measurement ruler').check();
  await page.getByLabel('Ruler units').selectOption('cm');
  await expect(page.getByRole('img', { name: 'Drawing ruler in centimetres' })).toContainText('cm');
  await controls().getByRole('button', { name: 'Zoom in', exact: true }).click();
  await expect(controls().locator('.studio-canvas-toolbar').first()).toContainText('125%');
  await page.getByRole('button', { name: 'Show floor plan' }).click();
  await expect(controls().locator('.studio-canvas-toolbar').first()).toContainText('100%');
  await controls().getByRole('button', { name: 'Zoom out', exact: true }).click();
  await expect(controls().locator('.studio-canvas-toolbar').first()).toContainText('75%');
  await page.getByRole('button', { name: 'Hide floor plan' }).click();
  await expect(controls().locator('.studio-canvas-toolbar').first()).toContainText('125%');
  await expect(page.getByLabel('Ruler units')).toHaveValue('cm');
  await page.getByRole('button', { name: 'Show floor plan' }).click();
  await expect(controls().locator('.studio-canvas-toolbar').first()).toContainText('75%');
});
