import {test,expect} from '@playwright/test';
for(const width of [1440,390])test('wall drags cancel and undo atomically at '+width+'px',async({page})=>{
  await page.setViewportSize({width,height:1000});await page.goto('/configure');await page.locator('[data-rearrange-wall]').first().click();const d=page.getByRole('dialog',{name:/^Rearrange /});
  const labels=()=>d.getByRole('group',{name:'Select an element'}).getByRole('button').allInnerTexts();await expect(d.getByRole('group',{name:'Select an element'}).getByRole('button').first()).toBeVisible();const before=await labels();
  const grip=d.locator('[data-layout-resize]').nth(2),column=d.locator('[data-layout-column]').nth(2);
  const start=async()=>{await d.locator('svg').scrollIntoViewIfNeeded();const b=(await grip.boundingBox())!,c=(await column.boundingBox())!,units=Number(await column.getAttribute('width'));await page.mouse.move(b.x+b.width/2,b.y+b.height/2);await page.mouse.down();await page.mouse.move(b.x+b.width/2+c.width/units*3,b.y+b.height/2,{steps:8});};
  await start();await expect.poll(labels).not.toEqual(before);await page.keyboard.press('Escape');await page.mouse.up();await expect(d).toBeVisible();expect(await labels()).toEqual(before);await expect(d.getByRole('button',{name:'Undo',exact:true})).toBeDisabled();
  await start();await page.mouse.up();const resized=await labels();expect(resized).not.toEqual(before);const parse=(s:string)=>Number(/·\s*([\d.]+) in/.exec(s)![1]);expect(parse(resized[2])-parse(before[2])).toBeCloseTo(3,0);await d.getByRole('button',{name:'Undo',exact:true}).click();expect(await labels()).toEqual(before);await expect(d.getByRole('button',{name:'Undo',exact:true})).toBeDisabled();
  await start();await grip.dispatchEvent('pointercancel',{pointerId:1,isPrimary:true});await page.mouse.up();expect(await labels()).toEqual(before);await expect(d).toBeVisible();
  await d.getByRole('group',{name:'Select an element'}).getByRole('button').first().click();await d.getByRole('button',{name:'Move right',exact:true}).click();const edited=await labels();await start();await page.keyboard.press('Escape');await page.mouse.up();expect(await labels()).toEqual(edited);await d.getByRole('button',{name:'Undo',exact:true}).click();expect(await labels()).toEqual(before);
  for(const cancel of [true,false]){await d.locator('svg').scrollIntoViewIfNeeded();const first=(await d.locator('[data-layout-column]').first().boundingBox())!,third=(await d.locator('[data-layout-column]').nth(2).boundingBox())!;await page.mouse.move(first.x+first.width/2,first.y+first.height/2);await page.mouse.down();await page.mouse.move(third.x+third.width*.8,third.y+third.height/2,{steps:8});await expect.poll(labels).not.toEqual(before);if(cancel)await page.keyboard.press('Escape');await page.mouse.up();if(!cancel)await d.getByRole('button',{name:'Undo',exact:true}).click();expect(await labels()).toEqual(before);await expect(d.getByRole('button',{name:'Undo',exact:true})).toBeDisabled();}
  await page.keyboard.press('Escape');await expect(d).toBeHidden();await expect(page.locator('[data-rearrange-wall]').first()).not.toContainText('Customized');
});
