import { test, expect } from '@playwright/test';
test('production server restores a saved organizer and prepares print',async({page,context})=>{
  await context.addInitScript(()=>{window.print=()=>{};});
  await page.goto('/configure');await page.locator('[data-drawer-id]').first().click();
  const drawer=page.getByRole('dialog',{name:'Design drawer compartments'});await drawer.getByLabel('Organizer name').fill('Production organizer');await drawer.getByRole('button',{name:'Apply to drawer',exact:true}).click();
  await page.getByRole('button',{name:'Save',exact:true}).click();await expect(page.getByRole('button',{name:/Manage saved designs \(1\)/})).toBeVisible();await page.evaluate(()=>localStorage.removeItem('alveo-draft'));await page.reload();await page.getByRole('button',{name:/Manage saved designs/}).click();const library=page.getByRole('dialog',{name:'Saved designs'});await library.getByRole('button',{name:'Open',exact:true}).click();await library.getByRole('button',{name:'Open reviewed design'}).click();await page.locator('[data-drawer-id]').first().click();await expect(drawer.getByLabel('Organizer name')).toHaveValue('Production organizer');await drawer.getByRole('button',{name:'Close editor'}).click();
  await page.getByRole('button',{name:'Export',exact:true}).click();await page.getByRole('menuitem',{name:'Print options and preview'}).click();const popup=page.waitForEvent('popup');await page.getByRole('button',{name:'Print captured design'}).click();const print=await popup;await expect(print.getByRole('heading',{name:'Drawer organizer: Production organizer'})).toBeVisible();
});

test('production accepts a valid backup then rejects malformed optional data without overwriting it',async({page})=>{
 await page.goto('/configure');await page.getByRole('button',{name:'Save',exact:true}).click();const original=await page.evaluate(()=>JSON.parse(localStorage.getItem('alveo-saved-designs')!));original.designs[0].id='production-import';original.designs[0].name='Production imported';await page.getByRole('button',{name:/Manage saved designs/}).click();const d=page.getByRole('dialog',{name:'Saved designs'});await d.locator('summary').filter({hasText:'Restore, compare, tags, and updates'}).click();await d.getByLabel(/Restore JSON backup/).setInputFiles({name:'valid.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(original))});await d.getByRole('button',{name:'Merge 1 designs'}).click();await expect(d.getByText('Production imported',{exact:true})).toBeVisible();const before=await page.evaluate(()=>localStorage.getItem('alveo-saved-designs'));original.designs[0].config.planning=false;await d.getByLabel(/Restore JSON backup/).setInputFiles({name:'bad.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(original))});await expect(d.getByText(/config.planning/).first()).toBeVisible();expect(await page.evaluate(()=>localStorage.getItem('alveo-saved-designs'))).toBe(before);
});
