import { test, expect, type Page } from '@playwright/test';
import { DEFAULT_CONFIG } from '../../src/lib/design';
import { exportInventoryCSV } from '../../src/lib/inventoryPlanning';
const room=async(page:Page)=>{await page.goto('/configure?preset=4');await page.locator('summary').filter({hasText:'Room openings, wall preferences, and sizing assumptions'}).click();};
const editor=async(page:Page)=>{await page.locator('[data-drawer-id]').first().click();return page.getByRole('dialog',{name:'Design drawer compartments'});};
const advanced=async(page:Page)=>{const d=await editor(page);await d.locator('summary').filter({hasText:'Measurements, item fit, divider tools, and custom templates'}).click();return d;};

test('room objects duplicate, warn, filter, undo and preserve changes across reload',async({page})=>{
  await room(page);await page.getByRole('button',{name:'Add window',exact:true}).click();await page.getByLabel('Window 1 name',{exact:true}).fill('Garden');await page.getByLabel('Window 1 offset',{exact:true}).fill('190');await page.getByLabel('Window 1 offset',{exact:true}).press('Tab');await expect(page.getByText(/Window 1.*extends .*beyond the wall/)).toBeVisible();
  await page.getByRole('button',{name:'Duplicate window 1',exact:true}).click();await expect(page.getByLabel('Window 2 name',{exact:true})).toHaveValue('Garden copy');await expect(page.getByText(/Window 2.*wall reservation overlaps/)).toBeVisible();await page.getByRole('button',{name:'Remove window 2',exact:true}).click();await page.getByRole('button',{name:'Undo room object removal'}).click();await expect(page.getByLabel('Window 2 name',{exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Add obstacle',exact:true}).click();await page.getByRole('button',{name:'Duplicate obstacle 1'}).click();await expect(page.getByText(/Obstacle 2.*overlaps Obstacle 1/).first()).toBeVisible();await page.getByLabel('Find room objects').fill('Garden');await expect(page.getByLabel('Obstacle 1 label')).toHaveCount(0);
  await page.getByRole('button',{name:'Save',exact:true}).click();await page.reload();await page.locator('summary').filter({hasText:'Room openings, wall preferences, and sizing assumptions'}).click();await expect(page.getByLabel('Window 1 name',{exact:true})).toHaveValue('Garden');
});
test('depth preview, room shell comparison, opposite-wall offsets and door screening work',async({page})=>{
  await room(page);await page.getByLabel('LEFT WALL cabinet depth',{exact:true}).fill('18');await page.getByLabel('LEFT WALL cabinet depth',{exact:true}).press('Tab');await expect(page.getByRole('region',{name:'Cabinet depth preview'})).toBeVisible();await page.getByRole('button',{name:'Apply cabinet depth'}).click();
  await page.locator('summary').filter({hasText:'Reusable room shells'}).click();await page.getByLabel('Room shell name').fill('Measured bedroom');await page.getByRole('button',{name:'Save room shell',exact:true}).click();await page.getByRole('button',{name:'Add obstacle',exact:true}).click();await page.getByLabel('Obstacle 1 distance from right wall',{exact:true}).fill('30');await page.getByLabel('Obstacle 1 distance from right wall',{exact:true}).press('Tab');await expect(page.getByLabel('Obstacle 1 x',{exact:true})).toHaveValue('150');
  await page.getByLabel('Compare saved room shell').selectOption({index:1});await page.getByRole('button',{name:'Apply compared room shell'}).click();await expect(page.getByLabel('Obstacle 1 label')).toHaveCount(0);
  await page.getByLabel('Use measured door opening').check();await page.locator('summary').filter({hasText:'Capacity assumptions, allocation, and alternatives'}).click();await page.getByRole('button',{name:'Compare feasible drawer layouts'}).click();await expect(page.getByText('No drawer layout options meet',{exact:false})).toBeVisible();
});
test('room object editing works with keyboard controls',async({page})=>{
  await room(page);const add=page.getByRole('button',{name:'Add obstacle',exact:true});await add.focus();await page.keyboard.press('Enter');const label=page.getByLabel('Obstacle 1 label');await label.focus();await page.keyboard.press('Control+A');await page.keyboard.type('Keyboard column');await page.keyboard.press('Tab');await page.keyboard.press('Control+A');await page.keyboard.type('42');await page.keyboard.press('Tab');await expect(page.getByLabel('Obstacle 1 x',{exact:true})).toHaveValue('42');await page.getByRole('button',{name:'Remove obstacle 1'}).focus();await page.keyboard.press('Enter');await page.getByRole('button',{name:'Undo room object removal'}).focus();await page.keyboard.press('Enter');await expect(label).toHaveValue('Keyboard column');
});
test('construction, range selection, metadata paste, template rename/delete and discard summary work',async({page})=>{
  await page.goto('/configure');const d=await advanced(page);await d.getByRole('button',{name:'Create grid',exact:true}).click();await d.locator('summary').filter({hasText:'Divider construction and clearances'}).click();await d.getByLabel('Separate horizontal and vertical thickness').check();await d.getByLabel('vertical divider thickness',{exact:true}).fill('.5');await d.getByLabel('vertical divider thickness',{exact:true}).press('Tab');await d.getByLabel('Divider material density (kg/m³)').selectOption('650');await expect(d.getByText(/Estimated internal divider weight/)).toBeVisible();
  const cells=d.getByRole('button',{name:/^Compartment \d+:/});await cells.first().focus();await page.keyboard.press('Shift+ArrowRight');await page.keyboard.press('Shift+ArrowDown');await expect(d.locator('[data-multiselected=true]')).toHaveCount(4);await d.getByLabel('Compartment label',{exact:true}).fill('Copied contents');await d.getByRole('button',{name:'Copy selected cell details'}).click();await d.getByRole('button',{name:'Preview paste to selected cells'}).click();await d.getByRole('button',{name:'Confirm cell detail paste'}).click();
  await d.getByLabel('Template name',{exact:true}).fill('Travel');await d.getByRole('button',{name:'Save custom template'}).click();await d.getByLabel('Manage saved template').selectOption({index:1});await d.getByLabel('Template name',{exact:true}).fill('Travel renamed');await d.getByRole('button',{name:'Rename selected template'}).click();await expect(d.getByLabel('Manage saved template')).toContainText('Travel renamed');await d.getByRole('button',{name:'Delete selected template'}).click();await d.getByRole('button',{name:'Undo template deletion'}).click();await expect(d.getByLabel('Manage saved template')).toContainText('Travel renamed');await d.getByRole('button',{name:'Close editor'}).click();await expect(d.getByText('Discard unapplied changes?',{exact:false})).toBeVisible();await expect(d.getByText('Compartments: 1 → 4')).toBeVisible();
});
test('template changes from two tabs are serialized and refreshed',async({page,context})=>{
  await page.goto('/configure');const other=await context.newPage();await other.goto('/configure');const a=await advanced(page),b=await advanced(other);await a.getByLabel('Template name',{exact:true}).fill('First tab');await b.getByLabel('Template name',{exact:true}).fill('Second tab');await Promise.all([a.getByRole('button',{name:'Save custom template'}).click(),b.getByRole('button',{name:'Save custom template'}).click()]);await expect(a.getByLabel('Preview custom template')).toContainText('Second tab');await expect(b.getByLabel('Preview custom template')).toContainText('First tab');
});
test('applied organizer survives immediate page closure',async({page,context})=>{
  await page.goto('/configure');const d=await editor(page);await d.getByLabel('Organizer name').fill('Close immediately');await d.getByRole('button',{name:'Apply to drawer',exact:true}).click();await page.close();const reopened=await context.newPage();await reopened.goto('/configure');const restored=await editor(reopened);await expect(restored.getByLabel('Organizer name')).toHaveValue('Close immediately');
});
test('inventory CSV, member profiles, reserves and target counts persist',async({page})=>{
  await page.goto('/configure');await page.locator('summary').filter({hasText:'Household, seasonal inventory, and reserve capacity'}).click();await page.getByLabel('Household member name').fill('Alex');await page.getByRole('button',{name:'Assign entered inventory to member'}).click();await page.getByLabel('Inventory season').selectOption('seasonal');await page.getByLabel('Member Shirts & blouses',{exact:true}).fill('20');await page.getByRole('button',{name:'Apply combined household inventory'}).click();await page.locator('summary').filter({hasText:'Reserve and incremental demand'}).click();await page.getByLabel('Reserve Shirts & blouses (%)',{exact:true}).fill('25');
  const inventory={wardrobe:{...DEFAULT_CONFIG.wardrobe,shirts:40},shoes:DEFAULT_CONFIG.shoes};await page.getByLabel('Import inventory CSV').setInputFiles({name:'inventory.csv',mimeType:'text/csv',buffer:Buffer.from(exportInventoryCSV(inventory))});await page.getByRole('button',{name:'Apply inventory import'}).click();await page.getByRole('button',{name:'Save',exact:true}).click();const config=await page.evaluate(()=>JSON.parse(localStorage.getItem('alveo-saved-designs')!).designs[0].config);expect(config.wardrobe.shirts).toBe(40);expect(config.inventoryPlanning.reserve['wardrobe.shirts']).toBe(25);expect(config.inventoryPlanning.members[0].season).toBe('seasonal');
});
test('folders, favorites, coverage, replacement history and cleanup preview work',async({page})=>{
  await page.goto('/configure');await page.getByRole('button',{name:'Save',exact:true}).click();await page.getByRole('button',{name:/Manage saved designs/}).click();const d=page.getByRole('dialog',{name:'Saved designs'});await d.getByRole('button',{name:'Select visible'}).click();await d.locator('summary').filter({hasText:'Project folders, revisions, and cleanup'}).click();await d.getByLabel('Destination project folder').fill('Bedroom');await d.getByRole('button',{name:'Move selected to folder'}).click();await expect(d.getByText(/Project: Bedroom/)).toBeVisible();await d.getByRole('button',{name:'Pin favorite'}).click();await expect(d.getByRole('button',{name:'Unpin favorite'})).toBeVisible();await d.locator('summary').filter({hasText:'Restore, compare, tags, and updates'}).click();await d.getByRole('button',{name:'Preview replacement with current design'}).click();await d.getByRole('button',{name:'Replace saved configuration'}).click();await d.getByLabel('Earlier design revision').selectOption({index:1});await d.getByRole('button',{name:'Restore revision as independent copy'}).click();await expect(d.getByText('Design 1 (copy)',{exact:true})).toBeVisible();await d.getByRole('button',{name:'Preview selected library cleanup'}).click();await expect(d.getByRole('heading',{name:'Cleanup preview — 1 designs'})).toBeVisible();await d.getByRole('button',{name:'Cancel library cleanup'}).click();
});
test('partial backup recovery separates invalid records and warns about library size',async({page})=>{
  await page.goto('/configure');await page.getByRole('button',{name:'Save',exact:true}).click();await page.getByRole('button',{name:/Manage saved designs/}).click();const d=page.getByRole('dialog',{name:'Saved designs'});await d.locator('summary').filter({hasText:'Restore, compare, tags, and updates'}).click();await d.getByLabel('Warn above library size').fill('1');
  const good={id:'backup',name:'Recovered',savedAt:'2026-09-29',config:DEFAULT_CONFIG};await d.getByLabel(/Restore JSON backup/).setInputFiles({name:'mixed.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify({version:1,designs:[good,{...good,id:'broken',config:null}]}))});await expect(d.getByText('1 recoverable designs; 1 rejected records.')).toBeVisible();await d.getByRole('button',{name:'Review recoverable designs for import'}).click();await expect(d.getByRole('alert')).toContainText('above your 1-design warning threshold');await d.getByRole('button',{name:'Merge 1 designs'}).click();await expect(d.getByText('Recovered',{exact:true})).toBeVisible();
});
test('ruler, keyboard pan, zone navigation and captured print enhancements work',async({page,context})=>{
  await context.addInitScript(()=>{window.print=()=>{};});await page.goto('/configure?preset=4');await page.getByLabel('Show measurement ruler').check();await expect(page.getByRole('img',{name:'Drawing ruler in inches'})).toBeVisible();await page.getByRole('button',{name:'Zoom in',exact:true}).click();const canvas=page.getByRole('region',{name:'Drawing canvas. Use zoom controls and scroll to pan.'}).first();await canvas.focus();await page.keyboard.press('ArrowRight');await expect.poll(()=>canvas.evaluate(el=>el.scrollLeft)).toBeGreaterThan(0);
  await page.locator('summary').filter({hasText:'Capacity assumptions, allocation, and alternatives'}).click();await page.getByRole('button',{name:'Show RIGHT WALL zone 1',exact:true}).click();await expect(page.getByRole('button',{name:/EL-C · RIGHT WALL/})).toHaveAttribute('aria-pressed','true');
  await page.getByRole('button',{name:'Export',exact:true}).click();await page.getByRole('menuitem',{name:'Print options and preview'}).click();const d=page.getByRole('dialog',{name:'Print options and preview'});await d.getByRole('button',{name:'Selected wall only preset'}).click();await d.getByLabel('Include room opening and obstacle schedule').check();await d.getByRole('combobox',{name:'Paper size',exact:true}).selectOption('Letter');await d.getByRole('button',{name:'Preview page breaks'}).click();await expect(d.frameLocator('iframe').locator('.preview-page').first()).toBeVisible();const popup=page.waitForEvent('popup');await d.getByRole('button',{name:'Print captured design'}).click();const print=await popup;await expect(print.getByRole('heading',{name:'Room openings and obstacle schedule'})).toBeVisible();await print.close();await page.reload();await page.getByRole('button',{name:'Export',exact:true}).click();await page.getByRole('menuitem',{name:'Print options and preview'}).click();await expect(page.getByRole('combobox',{name:'Paper size',exact:true})).toHaveValue('Letter');
});
test('200 percent zoom and forced-colors keep dialogs usable',async({page})=>{
  await page.setViewportSize({width:720,height:600});await page.goto('/configure');await page.locator('[data-drawer-id]').first().waitFor();await page.evaluate(()=>document.documentElement.style.zoom='2');const d=await editor(page);expect(await d.evaluate(el=>el.scrollWidth<=el.clientWidth+1)).toBe(true);await page.emulateMedia({forcedColors:'active',reducedMotion:'reduce'});await expect(d.locator('[aria-pressed=true]').first()).toHaveCSS('outline-style','solid');await d.getByRole('button',{name:'Close editor'}).click();await page.getByRole('button',{name:'Save',exact:true}).click();await page.getByRole('button',{name:/Manage saved designs/}).click();await expect(page.getByRole('dialog',{name:'Saved designs'})).toBeVisible();await page.keyboard.press('Escape');await page.getByRole('button',{name:'Export',exact:true}).click();await page.getByRole('menuitem',{name:'Print options and preview'}).click();expect(await page.getByRole('dialog',{name:'Print options and preview'}).evaluate(el=>el.scrollWidth<=el.clientWidth+1)).toBe(true);
});
