import { test, expect } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import { readFile } from 'node:fs/promises';
const library=(page:any)=>page.getByRole('dialog',{name:'Saved designs'});
const openTools=async(page:any)=>{await page.getByRole('button',{name:/Manage saved designs/}).click();await library(page).locator('summary').filter({hasText:'Restore, compare, tags, and updates'}).click();};
test('validated restore previews collisions and preserves both original and imported designs',async({page})=>{
  await page.goto('/configure');await page.getByRole('button',{name:'Save',exact:true}).click();const raw=await page.evaluate(()=>localStorage.getItem('alveo-saved-designs')!);
  await openTools(page);const d=library(page);await d.locator('input[type=file]').setInputFiles({name:'backup.json',mimeType:'application/json',buffer:Buffer.from(raw)});
  await expect(d.getByText(/Existing ID or name/)).toBeVisible();await d.getByLabel('Import Design 1',{exact:true}).selectOption('skip');await expect(d.getByRole('button',{name:'Merge 0 designs'})).toBeDisabled();await d.getByLabel('Import Design 1',{exact:true}).selectOption('keep');await d.getByRole('button',{name:'Merge 1 designs'}).click();await expect(d.getByRole('checkbox')).toHaveCount(2);
  const saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('alveo-saved-designs')!).designs);expect(new Set(saved.map((s:any)=>s.id)).size).toBe(2);expect(saved[1].config).toEqual(saved[0].config);
  await d.locator('input[type=file]').setInputFiles({name:'bad.json',mimeType:'application/json',buffer:Buffer.from('{broken')});await expect(d.getByRole('checkbox')).toHaveCount(2);expect(await page.evaluate(()=>localStorage.getItem('alveo-saved-designs'))).not.toBeNull();
});
test('tags search, comparisons, replacement and rename focus operate on saved records',async({page})=>{
  await page.goto('/configure');await page.getByRole('button',{name:'Save',exact:true}).click();await page.getByRole('button',{name:'Wardrobe',exact:true}).click();await page.getByLabel('Shirts & Blouses',{exact:true}).fill('44');await page.getByLabel('Shirts & Blouses',{exact:true}).press('Tab');await openTools(page);const d=library(page);
  await d.getByRole('checkbox').check();await d.getByLabel('Project tags (comma separated)').fill('bedroom, client-a');await d.getByLabel('Project tags (comma separated)').press('Tab');await expect(d.getByText('Tags: bedroom, client-a')).toBeVisible();
  await d.getByRole('button',{name:'Preview replacement with current design'}).click();await expect(d.getByRole('table')).toBeVisible();await d.getByRole('button',{name:'Replace saved configuration'}).click();
  await expect.poll(()=>page.evaluate(()=>JSON.parse(localStorage.getItem('alveo-saved-designs')!).designs[0].config.wardrobe.shirts)).toBe(44);
  await d.getByRole('button',{name:'Rename',exact:true}).click();await d.getByLabel('Design name',{exact:true}).fill('Study');await d.getByRole('button',{name:'Save name'}).click();await expect(d.getByRole('button',{name:'Rename',exact:true})).toBeFocused();
  await d.getByLabel('Search saved designs').fill('client-a');await expect(d.getByRole('checkbox')).toHaveCount(1);await d.getByRole('button',{name:'Duplicate',exact:true}).click();await d.getByRole('button',{name:'Select visible'}).click();await d.getByRole('button',{name:'Compare selected designs'}).click();await expect(d.getByRole('table')).toBeVisible();
});
test('lock failures retain memory-only changes and explicit retry persists them',async({page})=>{
  await page.goto('/configure');await expect(page.getByText('Draft: Saved',{exact:false})).toBeVisible();
  await page.evaluate(()=>{const original=navigator.locks.request.bind(navigator.locks);(window as any).restoreLock=()=>Object.defineProperty(navigator.locks,'request',{value:original,configurable:true});Object.defineProperty(navigator.locks,'request',{value:()=>Promise.reject(new Error('lock failure')),configurable:true});});
  await page.getByRole('button',{name:'Save',exact:true}).click();await expect(page.getByText(/1 pending operations/)).toBeVisible();await expect(page.getByText(/Storage lock failed/)).toBeVisible();await page.evaluate(()=>(window as any).restoreLock());await page.getByRole('button',{name:'Retry pending saves'}).click();await expect(page.getByText(/0 pending operations/)).toBeVisible();expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('alveo-saved-designs')!).designs.length)).toBe(1);
});
test('raw recovery downloads corrupt data unchanged and pagehide flushes latest draft',async({page})=>{
  await page.goto('/configure');await page.evaluate(()=>localStorage.setItem('alveo-saved-designs','corrupt original'));await page.reload();const waiting=page.waitForEvent('download');await page.getByRole('button',{name:'Download raw recovery data'}).click();const recovery=JSON.parse(await readFile((await (await waiting).path())!,'utf8'));expect(recovery.named).toBe('corrupt original');expect(await page.evaluate(()=>localStorage.getItem('alveo-saved-designs'))).toBe('corrupt original');
  await page.getByRole('button',{name:'Wardrobe',exact:true}).click();const shirts=page.getByLabel('Shirts & Blouses',{exact:true});await shirts.fill('123');await shirts.press('Tab');await page.evaluate(()=>window.dispatchEvent(new Event('pagehide')));expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('alveo-draft')!).config.wardrobe.shirts)).toBe(123);
});
test('two tabs preserve concurrent rename duplicate and delete operations',async({page,context})=>{
  await page.goto('/configure');await page.getByRole('button',{name:'Save',exact:true}).click();await page.getByRole('button',{name:'Save',exact:true}).click();const other=await context.newPage();await other.goto('/configure');await page.getByRole('button',{name:/Manage saved designs/}).click();await other.getByRole('button',{name:/Manage saved designs/}).click();const a=library(page),b=library(other);
  await a.getByRole('button',{name:'Rename',exact:true}).last().click();await a.getByLabel('Design name',{exact:true}).fill('Concurrent name');await Promise.all([a.getByRole('button',{name:'Save name'}).click(),b.getByRole('button',{name:'Duplicate',exact:true}).first().click()]);
  await expect(a.getByRole('checkbox')).toHaveCount(3);await expect(b.getByText('Concurrent name',{exact:true})).toBeVisible();
  await Promise.all([a.getByRole('button',{name:'Delete',exact:true}).last().click(),b.getByRole('button',{name:'Duplicate',exact:true}).first().click()]);await expect(a.getByRole('checkbox')).toHaveCount(3);await expect(b.getByRole('checkbox')).toHaveCount(3);const items=await page.evaluate(()=>JSON.parse(localStorage.getItem('alveo-saved-designs')!).designs);expect(new Set(items.map((d:any)=>d.id)).size).toBe(3);
});
test('measured drawers, item fit, custom templates, divider movement and batch preview persist',async({page})=>{
  await page.goto('/configure');await page.locator('[data-drawer-id]').first().click();const d=page.getByRole('dialog',{name:'Design drawer compartments'});await d.getByRole('button',{name:'Split left / right',exact:true}).click();await d.locator('summary').filter({hasText:'Measurements, item fit, divider tools, and custom templates'}).click();
  await d.getByLabel('Use measured internal dimensions').check();await d.getByLabel('Measured width (in)').fill('20');await d.getByLabel('Measured depth (in)').fill('18');await d.getByLabel('Measured height (in)').fill('6');await d.getByLabel('Check an item’s fit').check();await d.getByLabel('Item width (in)').fill('22');await expect(d.getByText('Item does not fit. Quantity does not imply stacked fit.')).toBeVisible();await d.getByLabel('Compartment notes',{exact:true}).fill('Daily essentials');
  await d.getByLabel('Merge with adjacent compartment').selectOption({index:1});await d.getByLabel('Divider position',{exact:true}).fill('60');await d.getByLabel('Template name',{exact:true}).fill('Travel insert');await d.getByRole('button',{name:'Save custom template'}).click();await d.getByLabel('Preview custom template').selectOption({index:1});await expect(d.getByText(/Scaled preview for this drawer/)).toBeVisible();await d.getByRole('button',{name:'Apply template preview'}).click();
  await d.getByRole('button',{name:'Apply to matching drawers'}).click();await expect(d.getByRole('heading',{name:'Batch application preview'})).toBeVisible();await d.getByRole('button',{name:'Confirm batch application'}).click();await page.getByRole('button',{name:'Save',exact:true}).click();const stored=await page.evaluate(()=>JSON.parse(localStorage.getItem('alveo-saved-designs')!).designs[0].config.drawerInteriors);expect(Object.values(stored).some((p:any)=>p.measured.width===20&&p.cells[0].notes==='Daily essentials')).toBe(true);
});
test('room openings, wall depths, alternatives and floor-plan wall navigation work',async({page})=>{
  await page.goto('/configure?preset=4');await page.locator('summary').filter({hasText:'Room openings, wall preferences, and sizing assumptions'}).click();await page.getByLabel('LEFT WALL cabinet depth',{exact:true}).fill('18');await page.getByLabel('LEFT WALL cabinet depth',{exact:true}).press('Tab');await page.getByRole('button',{name:'Apply cabinet depth'}).click();await page.getByLabel('Use measured door opening').check();await page.getByLabel('Door offset along wall',{exact:true}).fill('80');await page.getByLabel('Door offset along wall',{exact:true}).press('Tab');await page.getByRole('combobox',{name:'Door hinge',exact:true}).selectOption('right');await page.getByRole('button',{name:'Add window',exact:true}).click();await page.getByRole('button',{name:'Add obstacle',exact:true}).click();await page.getByRole('button',{name:'Show floor plan'}).click();await expect(page.locator('[data-wall-id="right"]:visible')).toBeVisible();await page.locator('[data-wall-id="right"]:visible').click();await expect(page.getByRole('button',{name:/EL-C · RIGHT WALL/})).toHaveAttribute('aria-pressed','true');
  await page.locator('summary').filter({hasText:'Capacity assumptions, allocation, and alternatives'}).click();await page.getByRole('button',{name:'Compare feasible drawer layouts'}).click();await expect(page.getByRole('button',{name:'Use many-small alternative'})).toBeVisible();
});
test('preview preferences, independent wall zoom, SVG IDs and high contrast survive expected transitions',async({page})=>{
  await page.goto('/configure?preset=4');await page.getByRole('checkbox',{name:'Dimensions',exact:true}).uncheck();await page.getByRole('checkbox',{name:'High contrast drawing'}).check();await page.getByRole('button',{name:'Zoom in',exact:true}).click();await expect(page.getByText('125%',{exact:true}).first()).toBeVisible();await page.getByRole('button',{name:/EL-B · LEFT WALL/}).click();await expect(page.getByText('100%',{exact:true}).first()).toBeVisible();await page.getByRole('button',{name:/EL-A · BACK WALL/}).click();await expect(page.getByText('125%',{exact:true}).first()).toBeVisible();await page.getByRole('button',{name:'Enlarge drawing'}).click();
  const ids=await page.locator('svg [id]').evaluateAll(nodes=>nodes.map(n=>n.id));expect(new Set(ids).size).toBe(ids.length);await page.keyboard.press('Escape');await page.reload();await expect(page.getByRole('checkbox',{name:'Dimensions',exact:true})).not.toBeChecked();await expect(page.getByRole('checkbox',{name:'High contrast drawing'})).toBeChecked();
});
test('configured print uses selected sections and downloads the identical configuration snapshot',async({page,context})=>{
  await context.addInitScript(()=>{window.print=()=>{document.body.dataset.printed='yes';};});await page.goto('/configure?preset=4');await page.getByRole('button',{name:'Export',exact:true}).click();await page.getByRole('menuitem',{name:'Print options and preview',exact:true}).click();const d=page.getByRole('dialog',{name:'Print options and preview'});await d.getByLabel('Project title',{exact:true}).fill('Study project');await d.getByRole('combobox',{name:'Paper size',exact:true}).selectOption('Letter');await d.getByRole('combobox',{name:'Page orientation',exact:true}).selectOption('landscape');await d.getByRole('checkbox',{name:'LEFT WALL',exact:true}).uncheck();await d.getByLabel('Download editable JSON with this print').check();await d.getByLabel('Include estimated materials worksheet').check();const download=page.waitForEvent('download'),popup=page.waitForEvent('popup');await d.getByRole('button',{name:'Print captured design'}).click();const print=await popup;await expect(print.locator('body')).toHaveAttribute('data-printed','yes');await expect(print.getByRole('heading',{name:'Study project',exact:true})).toBeVisible();await expect(print.getByRole('heading',{name:'LEFT WALL (EL-B)',exact:true})).toHaveCount(0);const backup=JSON.parse(await readFile((await (await download).path())!,'utf8'));expect(backup.designs[0].config.closetType).toBe('island');await expect(print.getByText(/Alvéo plan v1/)).toBeVisible();
});
test('expanded planning and export controls pass accessibility checks',async({page})=>{
  await page.goto('/configure');await page.locator('summary').filter({hasText:'Room openings, wall preferences, and sizing assumptions'}).click();await page.getByLabel('Use measured door opening').check();await page.getByLabel('Door offset along wall',{exact:true}).fill('80');await page.getByLabel('Door offset along wall',{exact:true}).press('Tab');await page.getByRole('button',{name:'Add window',exact:true}).click();const result=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();expect(result.violations.map(v=>({id:v.id,nodes:v.nodes.map(n=>n.target)}))).toEqual([]);
});


