'use client';
import { useEffect, useId, useLayoutEffect, useRef, useState } from 'react';
import { namespaceSVG } from '@/lib/preview';
export interface CanvasView {zoom:number;left:number;top:number;}
export function DrawingCanvas({svg,onDrawerClick,onObjectClick,viewKey='drawing',views,selectedDrawer,selectedZone,highContrast=false}:{svg:string;onObjectClick?:(kind:'wall'|'obstacle',id:string)=>void;onDrawerClick?:(id:string)=>void;viewKey?:string;views?:Map<string,CanvasView>;selectedDrawer?:string|null;selectedZone?:number|null;highContrast?:boolean}){
  const saved=views?.get(viewKey),[zoom,setZoom]=useState(saved?.zoom??1);
  const id=useId().replace(/[^a-zA-Z0-9]/g,''),normal=useRef<HTMLDivElement>(null),large=useRef<HTMLDivElement>(null),dialog=useRef<HTMLDialogElement>(null);
  const initialView=useRef(saved);
  const [rulerUnit,setRulerUnit]=useState('in');
  const [showRuler,setShowRuler]=useState(false),[ruler,setRuler]=useState({width:0,origin:0,scale:1,canvas:1,viewport:1,scroll:0});
  useEffect(()=>{const el=normal.current;if(!el)return;const update=()=>{const drawing=el.querySelector("svg");if(drawing)setRuler({width:Number(drawing.dataset.rulerWidth??0),origin:Number(drawing.dataset.rulerOrigin??0),scale:Number(drawing.dataset.rulerScale??1),canvas:drawing.viewBox.baseVal.width,viewport:el.clientWidth,scroll:el.scrollLeft});};update();const observer=new ResizeObserver(update);observer.observe(el);el.addEventListener("scroll",update);return()=>{observer.disconnect();el.removeEventListener("scroll",update);};},[svg]);
  useEffect(()=>{for(const el of [normal.current,large.current]){el?.querySelectorAll<SVGElement>("[data-zone-index]").forEach(node=>{const active=Number(node.dataset.zoneIndex)===selectedZone;node.style.stroke=active?"#2456a1":"none";node.style.strokeWidth=active?"2":"0";if(active&&el===normal.current)node.scrollIntoView({block:"nearest",inline:"center"});});}},[selectedZone,svg]);
  const pendingScroll=useRef<{el:HTMLDivElement;left:number;top:number;zoom:number}|null>(null);
  const points=useRef(new Map<number,{x:number;y:number}>()),drag=useRef<{x:number;y:number;left:number;top:number}|null>(null),pinch=useRef<number|null>(null),moved=useRef(false);
  const resize=(next:number,el:HTMLDivElement,x=el.clientWidth/2,y=el.clientHeight/2)=>{
    const bounded=Math.max(.25,Math.min(4,next)),ratio=bounded/zoom,left=(el.scrollLeft+x)*ratio-x,top=(el.scrollTop+y)*ratio-y;
    pendingScroll.current={el,left,top,zoom:bounded};setZoom(bounded);
  };
  useLayoutEffect(()=>{const pending=pendingScroll.current;if(!pending)return;const {el,left,top,zoom:nextZoom}=pending;const observer=new ResizeObserver(()=>{if(pendingScroll.current!==pending||!el.firstElementChild||Math.abs(el.firstElementChild.getBoundingClientRect().width-el.clientWidth*nextZoom)>4)return;pendingScroll.current=null;observer.disconnect();el.scrollLeft=left;el.scrollTop=top;if(el===normal.current)views?.set(viewKey,{zoom:nextZoom,left:el.scrollLeft,top:el.scrollTop});});if(el.firstElementChild)observer.observe(el.firstElementChild);return()=>observer.disconnect();},[zoom,viewKey,views]);
  useEffect(()=>{const initial=initialView.current;if(normal.current&&initial){normal.current.scrollLeft=initial.left;normal.current.scrollTop=initial.top;}},[]); // instance is keyed by wall
  useEffect(()=>{
    const elements=[normal.current,large.current].filter(Boolean) as HTMLDivElement[];
    const wheel=(e:WheelEvent)=>{if(!e.ctrlKey&&!e.metaKey)return;e.preventDefault();const el=e.currentTarget as HTMLDivElement,bounds=el.getBoundingClientRect();resize(zoom*Math.exp(-e.deltaY*.005),el,e.clientX-bounds.left,e.clientY-bounds.top);};
    const keydown=(e:KeyboardEvent)=>{if(e.target!==e.currentTarget)return;const el=e.currentTarget as HTMLDivElement,step=e.shiftKey?120:40;if(e.key.toLowerCase()==='c'&&selectedZone!==null&&selectedZone!==undefined){e.preventDefault();const node=Array.from(el.querySelectorAll<SVGElement>('[data-zone-index]')).find(n=>Number(n.dataset.zoneIndex)===selectedZone);if(node){const a=node.getBoundingClientRect(),b=el.getBoundingClientRect();el.scrollBy({left:a.left+a.width/2-b.left-b.width/2,top:a.top+a.height/2-b.top-b.height/2});}return;}if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();el.scrollBy({left:e.key==='ArrowLeft'?-step:e.key==='ArrowRight'?step:0,top:e.key==='ArrowUp'?-step:e.key==='ArrowDown'?step:0});}};
    elements.forEach(el=>{el.addEventListener('wheel',wheel,{passive:false});el.addEventListener('keydown',keydown);});
    return()=>elements.forEach(el=>{el.removeEventListener('wheel',wheel);el.removeEventListener('keydown',keydown);});
  });
  const activate=(target:EventTarget)=>{if(moved.current)return;const drawer=(target as Element).closest('[data-drawer-id]')?.getAttribute('data-drawer-id');if(drawer){dialog.current?.close();onDrawerClick?.(drawer);return;}for(const kind of ['wall','obstacle'] as const){const id=(target as Element).closest(`[data-${kind}-id]`)?.getAttribute(`data-${kind}-id`);if(id){onObjectClick?.(kind,id);return;}}};
  const view=(expanded=false)=><div ref={expanded?large:normal} role="region" tabIndex={0} aria-label="Drawing canvas. Use zoom controls and scroll to pan." className={'overflow-auto max-h-[70vh] border rounded cursor-grab '+(highContrast?'drawing-high-contrast':'')} style={{touchAction:'none'}}
    onScroll={e=>{if(!expanded)views?.set(viewKey,{zoom,left:e.currentTarget.scrollLeft,top:e.currentTarget.scrollTop});}}
    onPointerDown={e=>{moved.current=false;points.current.set(e.pointerId,{x:e.clientX,y:e.clientY});drag.current={x:e.clientX,y:e.clientY,left:e.currentTarget.scrollLeft,top:e.currentTarget.scrollTop};if(!(e.target as Element).closest('[data-drawer-id],[data-wall-id],[data-obstacle-id]'))e.currentTarget.setPointerCapture(e.pointerId);}}
    onPointerMove={e=>{
      if(!points.current.has(e.pointerId))return;points.current.set(e.pointerId,{x:e.clientX,y:e.clientY});
      if(points.current.size===2){const [a,b]=Array.from(points.current.values()),distance=Math.hypot(a.x-b.x,a.y-b.y),bounds=e.currentTarget.getBoundingClientRect();if(pinch.current)resize(zoom*distance/pinch.current,e.currentTarget,(a.x+b.x)/2-bounds.left,(a.y+b.y)/2-bounds.top);pinch.current=distance;moved.current=true;}
      else if(drag.current){if(Math.hypot(e.clientX-drag.current.x,e.clientY-drag.current.y)>5)moved.current=true;e.currentTarget.scrollLeft=drag.current.left+drag.current.x-e.clientX;e.currentTarget.scrollTop=drag.current.top+drag.current.y-e.clientY;}
    }} onPointerUp={e=>{points.current.delete(e.pointerId);drag.current=null;pinch.current=null;}} onPointerCancel={e=>{points.current.delete(e.pointerId);drag.current=null;pinch.current=null;}}>
    <div role="presentation" onClick={e=>activate(e.target)} onKeyDown={e=>{if((e.key==='Enter'||e.key===' ')&&(e.target as Element).closest('[data-drawer-id],[data-wall-id],[data-obstacle-id]')){e.preventDefault();moved.current=false;activate(e.target);}}} style={{width:`${zoom*100}%`}} dangerouslySetInnerHTML={{__html:namespaceSVG(svg,`${id}-${expanded?'large':'normal'}`)}}/>
  </div>;
  useEffect(()=>{for(const el of [normal.current,large.current]){el?.querySelectorAll('[data-drawer-id]').forEach(node=>{const selected=node.getAttribute('data-drawer-id')===selectedDrawer;(node as SVGElement).style.filter=selected?'drop-shadow(0 0 5px #1d4ed8)':'';node.setAttribute('data-selected',String(selected));});}},[selectedDrawer,svg]);
  const controls=(expanded=false)=>{const region=()=>expanded?large.current:normal.current;return <div className="studio-canvas-toolbar flex flex-wrap items-center gap-3 text-sm my-2"><button aria-label="Zoom out" onClick={()=>{const el=region();if(el)resize(zoom-.25,el);}}>−</button><span>{Math.round(zoom*100)}%</span><button aria-label="Zoom in" onClick={()=>{const el=region();if(el)resize(zoom+.25,el);}}>+</button><button onClick={()=>{pendingScroll.current=null;setZoom(1);const el=region();if(el){el.scrollLeft=0;el.scrollTop=0;}views?.set(viewKey,{zoom:1,left:0,top:0});}}>Reset view</button><button onClick={()=>{const el=region(),drawing=el?.querySelector('svg');if(el&&drawing){const box=drawing.viewBox.baseVal;resize(Math.min(1,el.clientHeight/(el.clientWidth*box.height/box.width)),el,0,0);}}}>Fit to viewport</button></div>;};
  return <div><style>{'.drawing-high-contrast svg [fill]:not(text):not(tspan):not([fill="transparent"]):not([fill="none"]){fill:#fff!important}.drawing-high-contrast svg [stroke]{stroke:#111!important}.drawing-high-contrast svg text,.drawing-high-contrast svg tspan{fill:#111!important}'}</style>{controls()}<details className="studio-canvas-help"><summary>Canvas shortcuts</summary><p className="text-xs">Focus the canvas and use arrow keys to pan; Shift + arrow moves farther. Ctrl/Command + wheel zooms. Press C to center the highlighted zone.</p></details><label className="studio-ruler-label text-sm"><input type="checkbox" checked={showRuler} onChange={e=>setShowRuler(e.target.checked)}/> Show measurement ruler</label>{showRuler&&<label className="block">Ruler units<select value={rulerUnit} onChange={e=>setRulerUnit(e.target.value)}><option value="in">Inches</option><option value="cm">Centimetres</option></select></label>}{showRuler&&<div role="img" aria-label={rulerUnit==='in'?'Drawing ruler in inches':'Drawing ruler in centimetres'} className="relative h-8 overflow-hidden border-b text-xs">{Array.from({length:13},(_,i)=>ruler.width*i/12).map((n,i)=><span key={i} className="absolute border-l pl-1 whitespace-nowrap" style={{left:(ruler.origin+n*ruler.scale)/ruler.canvas*ruler.viewport*zoom-ruler.scroll}}>{(n*(rulerUnit==='cm'?2.54:1)).toFixed(1)} {rulerUnit}</span>)}</div>}<button className="studio-enlarge text-sm mb-2" onClick={()=>dialog.current?.showModal()}>Enlarge drawing</button>{view()}<dialog ref={dialog} aria-label="Enlarged closet drawing" className="w-[95vw] max-w-none p-5 rounded-xl backdrop:bg-black/40"><button onClick={()=>dialog.current?.close()}>Close drawing</button>{controls(true)}{view(true)}</dialog></div>;
}







