'use client';
import { useState } from 'react';
import type { DrawerInterior, DrawerTarget } from '@/lib/drawers';
import { cellSize, moveDivider } from '@/lib/drawers';
import { achievableUsable, dividerLock, resizeCompartment } from '@/lib/drawerConstruction';
export function DrawerPrecision({plan,target,selected,neighbor,change}:{plan:DrawerInterior;target:DrawerTarget;selected:string;neighbor:string;change:(v:DrawerInterior)=>void}){
  const [width,setWidth]=useState(''),[depth,setDepth]=useState(''),[preview,setPreview]=useState<{before:DrawerInterior;after:DrawerInterior}|null>(null),[message,setMessage]=useState('');
  const lock=dividerLock(plan,selected,neighbor);
  const widthRange=achievableUsable(plan,target.drawer,selected,neighbor,'x'),depthRange=achievableUsable(plan,target.drawer,selected,neighbor,'y');
  const rangeLabel=(r:ReturnType<typeof achievableUsable>)=>lock?'Locked':!r?'Choose the adjacent neighbor above':r.feasible?`Achievable ${r.min.toFixed(2)}–${r.max.toFixed(2)} in usable`:'No feasible range at the configured minimum';
  const prepare=(axis:'x'|'y',raw:string)=>{if(lock){setMessage('Movement blocked by lock: '+lock);return;}const next=resizeCompartment(plan,target.drawer,selected,neighbor,axis,Number(raw));if(JSON.stringify(next)===JSON.stringify(plan)){setMessage('Choose an adjacent neighbor on this axis and a size inside the available interval.');return;}setPreview({before:structuredClone(plan),after:next});setMessage('');};
  return <details className="settings-precision border rounded p-2"><summary>Precise compartment sizing</summary><p className="settings-description">Choose the adjacent neighbor above. Its usable size changes with the shared divider.</p><div className="settings-field-grid"><div><label className="block">Requested usable width (in)<input className="border p-2 w-full" type="number" min={.01} step={.125} value={width} onChange={e=>setWidth(e.target.value)}/></label><button disabled={!neighbor} onClick={()=>prepare('x',width)}>Preview compartment width</button><p className="text-xs" data-achievable="width">{rangeLabel(widthRange)}</p></div><div><label className="block">Requested usable depth (in)<input className="border p-2 w-full" type="number" min={.01} step={.125} value={depth} onChange={e=>setDepth(e.target.value)}/></label><button disabled={!neighbor} onClick={()=>prepare('y',depth)}>Preview compartment depth</button><p className="text-xs" data-achievable="depth">{rangeLabel(depthRange)}</p></div></div><button disabled={!neighbor} onClick={()=>{if(lock){setMessage('Movement blocked by lock: '+lock);return;}setPreview({before:structuredClone(plan),after:moveDivider(plan,selected,neighbor,.5,0,target.drawer)});}}>Center shared divider</button>
    {preview&&<div className="settings-change-preview"><h3>Shared divider change preview</h3>{preview.before.cells.filter(c=>JSON.stringify(c)!==JSON.stringify(preview.after.cells.find(v=>v.id===c.id))).map(c=>{const before=cellSize(c!,target.drawer,preview.before),after=cellSize(preview.after.cells.find(v=>v.id===c!.id)!,target.drawer,preview.after);return <p key={c!.id}>{c!.label}: {before.width.toFixed(2)} × {before.depth.toFixed(2)} → {after.width.toFixed(2)} × {after.depth.toFixed(2)} in</p>;})}<button onClick={()=>{if(JSON.stringify(plan)!==JSON.stringify(preview.before)){setMessage('Arrangement changed; preview the move again.');return;}change(preview.after);setPreview(null);}}>Apply shared divider change</button><button onClick={()=>setPreview(null)}>Cancel shared divider change</button></div>}<p role="status">{message}</p></details>;
}
