'use client';
import { useState } from 'react';
import { combinedInventory, INVENTORY_KEYS, inventoryLabel, inventoryValue, readHousehold, setInventoryValue, validInventory } from '@/lib/inventoryPlanning';
import type { Inventory, InventoryPlanning } from '@/lib/inventoryPlanning';
import { downloadText } from '@/lib/download';
type Member=NonNullable<InventoryPlanning['members']>[number];
export function InventoryFields({value,onChange,prefix}:{value:Inventory;onChange:(v:Inventory)=>void;prefix:string}){return <div className="grid grid-cols-1 sm:grid-cols-2 gap-2 min-w-0">{INVENTORY_KEYS.map(key=><label className="text-sm min-w-0" key={key}>{prefix} {inventoryLabel(key)}<input className="border rounded p-2 w-full min-w-0" type="number" min={0} max={key.endsWith('.jewelry')?1:10000} value={inventoryValue(value,key)} onChange={e=>{const n=Number(e.target.value);if(Number.isInteger(n)&&n>=0&&n<=(key.endsWith('.jewelry')?1:10000))onChange(setInventoryValue(value,key,n));}}/></label>)}</div>;}
export function HouseholdProfiles({options,current,update,onApply}:{options:InventoryPlanning;current:Inventory;update:(v:Partial<InventoryPlanning>)=>void;onApply:(v:Inventory)=>void}){
  const [name,setName]=useState(''),[memberId,setMemberId]=useState(''),[deleted,setDeleted]=useState<Member|null>(null),[excluded,setExcluded]=useState(new Set<string>()),[incoming,setIncoming]=useState<ReturnType<typeof readHousehold>|null>(null),[skip,setSkip]=useState(new Set<string>()),[includeNotes,setIncludeNotes]=useState(false),[message,setMessage]=useState('');
  const members=options.members??[],member=members.find(m=>m.id===memberId),included=members.filter(m=>!excluded.has(m.id)),combined=combinedInventory(included),field='border rounded p-2 w-full';
  return <div className="min-w-0"><label className="block">Household member name<input className={field} maxLength={80} value={name} onChange={e=>setName(e.target.value)}/></label><button disabled={!name.trim()||members.length>=10} onClick={()=>{const id=crypto.randomUUID();update({members:[...members,{id,name:name.trim(),season:'everyday',inventory:structuredClone(current)}]});setMemberId(id);}}>Assign entered inventory to member</button>
    <label className="block">Edit inventory profile<select className={field} value={memberId} onChange={e=>{setMemberId(e.target.value);setName(members.find(m=>m.id===e.target.value)?.name??'');}}><option value="">Choose member</option>{members.map(m=><option key={m.id} value={m.id}>{m.name} — {m.season}</option>)}</select></label>
    {member&&<details open className="border p-2 min-w-0"><summary>{member.name} inventory</summary><button disabled={!name.trim()} onClick={()=>update({members:members.map(m=>m.id===member.id?{...m,name:name.trim()}:m)})}>Rename inventory profile</button><button disabled={!name.trim()||members.length>=10} onClick={()=>{const copy={...structuredClone(member),id:crypto.randomUUID(),name:name.trim()};update({members:[...members,copy]});setMemberId(copy.id);}}>Duplicate inventory profile</button><label className="block">Inventory season<select className={field} value={member.season} onChange={e=>update({members:members.map(m=>m.id===member.id?{...m,season:e.target.value as 'everyday'}:m)})}><option value="everyday">Everyday</option><option value="seasonal">Seasonal</option></select></label><InventoryFields value={member.inventory} prefix="Member" onChange={inventory=>update({members:members.map(m=>m.id===member.id?{...m,inventory}:m)})}/><button onClick={()=>{setDeleted(member);update({members:members.filter(m=>m.id!==member.id)});setMemberId('');}}>Remove inventory profile</button></details>}
    {deleted&&<button disabled={members.length>=10} onClick={()=>{if(members.some(m=>m.id===deleted.id)){setMessage('That profile already exists.');return;}update({members:[...members,deleted]});setDeleted(null);}}>Undo profile removal</button>}
    {members.map(m=><label key={m.id} className="block"><input type="checkbox" checked={!excluded.has(m.id)} onChange={e=>setExcluded(old=>{const next=new Set(old);e.target.checked?next.delete(m.id):next.add(m.id);return next;})}/> Include {m.name} in combined inventory</label>)}
    {(['everyday','seasonal'] as const).map(season=>{const list=included.filter(m=>m.season===season),totals=combinedInventory(list);return <div key={season}><p>{season}: {INVENTORY_KEYS.filter(k=>!k.endsWith('.jewelry')).reduce((n,k)=>n+inventoryValue(totals,k),0)} items/pairs across selected profiles; jewelry {totals.wardrobe.jewelry?'requested':'not requested'}.</p><button disabled={!list.length||!validInventory(totals)} onClick={()=>onApply(totals)}>Apply {season} inventory</button></div>;})}
    <button disabled={!included.length||!validInventory(combined)} onClick={()=>onApply(combined)}>Apply combined household inventory</button>{!validInventory(combined)&&<p role="alert">Combined inventory exceeds 10,000 in a category.</p>}
    <button onClick={()=>downloadText(JSON.stringify({version:1,household:{members,notes:options.notes}}),'alveo-household.json')}>Download household profiles and notes</button>
    <label className="block">Import household profiles<input className="block w-full max-w-full" type="file" accept=".json,application/json" onChange={async e=>{const file=e.target.files?.[0];e.target.value='';setIncoming(null);if(!file)return;try{if(file.size>1024*1024)throw new Error('Household file exceeds 1 MB.');setIncoming(readHousehold(await file.text()));setSkip(new Set());setIncludeNotes(false);}catch(error){setMessage((error as Error).message);}}}/></label>
    {incoming&&<div><h3>Household import preview</h3>{incoming.members?.map(m=><label key={m.id} className="block"><input type="checkbox" checked={!skip.has(m.id)} onChange={e=>setSkip(old=>{const next=new Set(old);e.target.checked?next.delete(m.id):next.add(m.id);return next;})}/> Keep {m.name}{members.some(v=>v.id===m.id||v.name===m.name)?' — conflict: keep as a new independent profile':''}</label>)}<label className="block"><input type="checkbox" checked={includeNotes} onChange={e=>setIncludeNotes(e.target.checked)}/> Replace measurement notes with imported notes</label><button onClick={()=>{const copies=(incoming.members??[]).filter(m=>!skip.has(m.id)).map(m=>({...m,id:crypto.randomUUID()}));if(members.length+copies.length>10){setMessage('Select fewer profiles; the limit is 10.');return;}update({members:[...members,...copies],...(includeNotes?{notes:incoming.notes??{}}:{})});setIncoming(null);}}>Confirm household import</button><button onClick={()=>setIncoming(null)}>Cancel household import</button></div>}<p role="status">{message}</p>
  </div>;
}
