'use client';
import { HouseholdProfiles, InventoryFields } from './HouseholdProfiles';
import { useState } from 'react';
import type { ClosetConfiguration, ClosetLayout } from '@/types/closet';
import { EMPTY_INVENTORY, INVENTORY_KEYS, inventoryLabel, reserveInventory, exportInventoryCSV, incrementalDemand, inventoryValue, readInventoryCSV, setInventoryValue, validInventory } from '@/lib/inventoryPlanning';
import type { Inventory, InventoryPlanning as Options } from '@/lib/inventoryPlanning';
import { downloadText } from '@/lib/download';

export function InventoryPlanning({config,layout,onChange}:{config:Partial<ClosetConfiguration>;layout:ClosetLayout;onChange:(p:Partial<ClosetConfiguration>)=>void}){
  const current:Inventory={wardrobe:config.wardrobe??EMPTY_INVENTORY.wardrobe,shoes:config.shoes??EMPTY_INVENTORY.shoes},options=config.inventoryPlanning??{},update=(patch:Partial<Options>)=>onChange({inventoryPlanning:{...options,...patch}});
  const [csv,setCSV]=useState<Inventory|null>(null),[message,setMessage]=useState('');
  const target=options.target;
  const [resetPreview,setResetPreview]=useState(false),[targetPreview,setTargetPreview]=useState<Inventory|null>(null),[undoTarget,setUndoTarget]=useState<{before:Inventory;after:Inventory}|null>(null);
  const contributors=(label:string)=>label.startsWith('Long')?['wardrobe.longDresses']:label.startsWith('Short')?['wardrobe.shirts','wardrobe.shortJackets','wardrobe.pants','wardrobe.suits']:label==='Folded storage'?['wardrobe.tShirts','wardrobe.sweaters','wardrobe.jeans','wardrobe.underwear']:INVENTORY_KEYS.filter(k=>k.split('.')[1].toLowerCase()===label.toLowerCase());
  return <details className="border rounded p-3 my-3"><summary>Household, seasonal inventory, and reserve capacity</summary>
    <p className="text-sm">Inventory profiles are drafts until you apply their combined counts. Reserve percentages increase generated demand while preserving the entered counts.</p>
    <HouseholdProfiles options={options} current={current} update={update} onApply={onChange}/>
    <button onClick={()=>setResetPreview(true)}>Preview reserve reset</button>{resetPreview&&<div><h3>Reserve reset demand changes</h3>{INVENTORY_KEYS.filter(k=>!k.endsWith('.jewelry')&&(options.reserve?.[k]??0)>0).map(k=><p key={k}>{inventoryLabel(k)}: {inventoryValue(reserveInventory(current,options.reserve),k)} → {inventoryValue(current,k)} items</p>)}<button onClick={()=>{update({reserve:{}});setResetPreview(false);}}>Reset all reserve percentages</button><button onClick={()=>setResetPreview(false)}>Cancel reserve reset</button></div>}
    <details className="border p-2 my-2"><summary>Reserve and incremental demand</summary>{INVENTORY_KEYS.filter(k=>!k.endsWith('.jewelry')).map(key=><label className="block text-sm" key={key}>Reserve {inventoryLabel(key)} (%)<input className="border rounded p-2 w-full" aria-label={`Reserve ${inventoryLabel(key)} (%)`} aria-describedby={`reserve-help-${key}`} type="number" min={0} max={100} value={options.reserve?.[key]??0} onChange={e=>{const n=Number(e.target.value);if(Number.isFinite(n)&&n>=0&&n<=100)update({reserve:{...options.reserve,[key]:n}});}}/><span id={`reserve-help-${key}`}>One additional item needs {incrementalDemand(key)} before reserve.</span></label>)}</details>
    {INVENTORY_KEYS.filter(key=>inventoryValue(current,key)>1000).map(key=><p role="status" key={key}>Unusually high inventory: {inventoryLabel(key)} = {inventoryValue(current,key)}. Confirm this quantity; it has not been changed.</p>)}
    <details className="border p-2 my-2"><summary>Current and target inventory</summary><button onClick={()=>update({target:structuredClone(current)})}>Capture current as target</button>{target&&<><InventoryFields value={target} onChange={v=>update({target:v})} prefix="Target"/><table className="w-full text-sm"><caption>Current versus target counts</caption><thead><tr><th>Category</th><th>Current</th><th>Target</th><th>Change</th></tr></thead><tbody>{INVENTORY_KEYS.map(key=><tr key={key}><th>{inventoryLabel(key)}</th><td>{inventoryValue(current,key)}</td><td>{inventoryValue(target,key)}</td><td>{inventoryValue(target,key)-inventoryValue(current,key)}</td></tr>)}</tbody></table><button onClick={()=>setTargetPreview(structuredClone(target))}>Apply target counts</button></>}</details>
    {targetPreview&&<div><h3>Target application changes</h3>{INVENTORY_KEYS.filter(k=>inventoryValue(current,k)!==inventoryValue(targetPreview,k)).map(k=><p key={k}>{inventoryLabel(k)}: {inventoryValue(current,k)} → {inventoryValue(targetPreview,k)}</p>)}<button onClick={()=>{setUndoTarget({before:structuredClone(current),after:targetPreview});onChange(targetPreview);setTargetPreview(null);}}>Confirm target inventory</button><button onClick={()=>setTargetPreview(null)}>Cancel target application</button></div>}
    {undoTarget&&<button onClick={()=>{if(JSON.stringify(current)!==JSON.stringify(undoTarget.after)){setMessage('Inventory changed since target application. Undo would overwrite those changes.');return;}onChange(undoTarget.before);setUndoTarget(null);}}>Undo target inventory</button>}
    <button onClick={()=>downloadText(exportInventoryCSV(current),'alveo-inventory.csv','text/csv')}>Download inventory CSV / template</button>
    <label className="block">Import inventory CSV<input className="block w-full max-w-full" type="file" accept=".csv,text/csv" onChange={async e=>{const file=e.target.files?.[0];e.target.value='';if(!file)return;try{if(file.size>65536)throw new Error('Inventory CSV exceeds 64 KB.');setCSV(readInventoryCSV(await file.text()));}catch(error){setMessage((error as Error).message);}}}/></label>
    {csv&&<div><h3>Inventory import preview</h3>{INVENTORY_KEYS.map(key=><p className="text-sm" key={key}>{inventoryLabel(key)}: {inventoryValue(current,key)} → {inventoryValue(csv,key)}</p>)}<button onClick={()=>{onChange(csv);setCSV(null);setMessage('Imported inventory counts applied.');}}>Apply inventory import</button><button onClick={()=>setCSV(null)}>Cancel inventory import</button></div>}
    <details className="border p-2 my-2"><summary>Exceptional measurement notes</summary>{(['long','short','shoes'] as const).map(key=><label key={key} className="block">{key} measurement notes<textarea className="border rounded p-2 w-full" maxLength={500} value={options.notes?.[key]??''} onChange={e=>update({notes:{...options.notes,[key]:e.target.value}})}/></label>)}</details>
    <h3>Inventory behind capacity shortfalls</h3>{layout.capacity?.filter(row=>row.required>row.available).map(row=><p className="text-sm" key={row.label}>{row.label}: {contributors(row.label).map(key=>`${inventoryLabel(key)}: ${inventoryValue(current,key)} entered, ${options.reserve?.[key]??0}% reserve`).join('; ')}. Demand {row.required.toFixed(2)} versus {row.available.toFixed(2)} available {row.unit}.</p>)}
    <p role="status">{message}</p>
  </details>;
}
