'use client';
import { useState } from 'react';
import type { SavedDesign } from '@/types/closet';
import type { LibraryActions } from './LibraryTools';
import { duplicateConfigurations } from '@/lib/libraryOrganization';
import { downloadText } from '@/lib/download';
import { serializeDesigns } from '@/lib/storage';
import { DesignComparison } from './LibraryTools';
export function LibraryOrganization({designs,selected,actions}:{designs:SavedDesign[];selected:Set<string>;actions:LibraryActions}){
  const [sourceFolder,setSourceFolder]=useState(''),[tagText,setTagText]=useState(''),[tagMode,setTagMode]=useState('add'),[batch,setBatch]=useState<Array<{before:SavedDesign;folder?:string;tags?:string[]}>|null>(null);
  const [folder,setFolder]=useState(''),[cleanup,setCleanup]=useState<SavedDesign[]|null>(null),[message,setMessage]=useState(''),[revision,setRevision]=useState(''),[busy,setBusy]=useState(false);
  const picked=designs.filter(d=>selected.has(d.id)),one=picked.length===1?picked[0]:null,old=one?.revisions?.find(v=>v.id===revision);
  const run=async(work:()=>Promise<boolean>)=>{setBusy(true);try{setMessage(await work()?'Saved to this device.':'Could not persist changes. Check recovery status.');}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}};
  return <details className="border rounded p-3 my-3"><summary>Project folders, revisions, and cleanup</summary><fieldset disabled={busy}>
    <label className="block">Source project folder<select className="border p-2 w-full" value={sourceFolder} onChange={e=>setSourceFolder(e.target.value)}><option value="">Choose source folder</option>{Array.from(new Set(designs.map(d=>d.folder).filter(Boolean))).map(v=><option key={v}>{v}</option>)}</select></label>
    <button disabled={!sourceFolder||!folder.trim()||sourceFolder===folder.trim()} onClick={()=>setBatch(designs.filter(d=>d.folder===sourceFolder).map(before=>({before:structuredClone(before),folder:folder.trim()})))}>Preview folder rename or merge</button><p className="text-xs">Use a new destination name to rename the folder, or an existing name to merge folders. Design IDs stay unchanged.</p>
    <label className="block">Bulk project tags<input className="border p-2 w-full" maxLength={490} value={tagText} onChange={e=>setTagText(e.target.value)}/></label><label>Tag operation<select className="border p-2" value={tagMode} onChange={e=>setTagMode(e.target.value)}><option value="add">Add tags</option><option value="remove">Remove tags</option></select></label><button disabled={!picked.length||!tagText.trim()} onClick={()=>{const tags=tagText.split(',').map(v=>v.trim()).filter(Boolean);setBatch(picked.map(before=>({before:structuredClone(before),tags:tagMode==='add'?Array.from(new Set([...(before.tags??[]),...tags])):(before.tags??[]).filter(t=>!tags.includes(t))})));}}>Preview bulk tag change</button>
    {batch&&<div><h3>Library metadata change preview</h3><ul>{batch.map(p=><li key={p.before.id}>{p.before.name} — {p.before.id}: {p.folder!==undefined?`${p.before.folder||'Unfiled'} → ${p.folder}`:`${(p.before.tags??[]).join(', ')} → ${p.tags?.join(', ')}`}</li>)}</ul><button disabled={!actions.metadataBatch} onClick={()=>{void run(()=>actions.metadataBatch!(batch));setBatch(null);}}>Apply previewed metadata changes</button><button onClick={()=>setBatch(null)}>Cancel metadata changes</button></div>}

    <label className="block">Destination project folder<input className="border rounded p-2 w-full" maxLength={80} value={folder} onChange={e=>setFolder(e.target.value)} list="project-folders"/></label><datalist id="project-folders">{Array.from(new Set(designs.map(d=>d.folder).filter(Boolean))).map(v=><option key={v}>{v}</option>)}</datalist><button disabled={!picked.length||!actions.organize} onClick={()=>void run(()=>actions.organize!(picked.map(d=>d.id),folder))}>Move selected to folder</button><p className="text-xs">Enter a new folder name, choose an existing one, or leave blank to remove the folder assignment. Tags remain separate.</p>
    {one&&<><label className="block">Earlier design revision<select className="border rounded p-2 w-full" value={revision} onChange={e=>setRevision(e.target.value)}><option value="">Choose a revision</option>{one.revisions?.map(r=><option value={r.id} key={r.id}>{new Date(r.savedAt).toLocaleString()}{r.note?' — '+r.note:''}</option>)}</select></label>{old&&<><DesignComparison designs={[one,{...one,id:'revision-preview',name:'Earlier revision',config:old.config}]}/><button disabled={!actions.restoreRevision} onClick={()=>void run(()=>actions.restoreRevision!(one.id,old.id))}>Restore revision as independent copy</button><button onClick={()=>downloadText(serializeDesigns([{id:crypto.randomUUID(),name:(one.name+' revision').slice(0,120),savedAt:old.savedAt,config:old.config}]),'alveo-design-revision.json')}>Download selected revision</button></>}<p className="text-xs">Replacements keep up to 10 earlier configurations on this device.</p></>}
    {duplicateConfigurations(designs).map((group,i)=><p className="text-sm" key={i}>Exact configuration duplicates: {group.map(d=>`${d.name} (${d.id})`).join('; ')}. No records are selected automatically.</p>)}
    <button disabled={!picked.length||!actions.removeMany} onClick={()=>setCleanup(structuredClone(picked))}>Preview selected library cleanup</button>
    {cleanup&&<div><h3>Cleanup preview — {cleanup.length} designs</h3><ul>{cleanup.map(d=><li key={d.id}>{d.name} — {d.id} — {d.folder||'No folder'}</li>)}</ul><p>These exact records, including their local revision history, will be removed. Download selected JSON first if you need a backup.</p><button onClick={()=>{void run(()=>actions.removeMany!(cleanup));setCleanup(null);}}>Remove previewed designs</button><button onClick={()=>setCleanup(null)}>Cancel library cleanup</button></div>}
    <p role="status">{message}</p></fieldset></details>;
}
