'use client';
import { useEffect, useState } from 'react';
import type { DrawerInterior, DrawerTarget } from '@/lib/drawers';
import { innerSize, interiorSVG, interiorWarnings } from '@/lib/drawers';
import { organizerChanges } from '@/lib/drawerConstruction';
import { downloadText } from '@/lib/download';
import { mutateTemplates, readTemplates, serializeTemplates, TEMPLATE_KEY } from '@/lib/organizerTemplates';
import type { OrganizerTemplate } from '@/lib/organizerTemplates';

export function OrganizerTemplates({plan,target,change}:{plan:DrawerInterior;target:DrawerTarget;change:(p:DrawerInterior)=>void}){
  const [compatible,setCompatible]=useState(false),[tags,setTags]=useState(''),[revision,setRevision]=useState(''),[bulk,setBulk]=useState<OrganizerTemplate[]|null>(null),[renameImports,setRenameImports]=useState<Record<string,string>>({}),[retry,setRetry]=useState<{fn:(v:OrganizerTemplate[])=>OrganizerTemplate[];success:string;done?:()=>void}|null>(null);
  const [templates,setTemplates]=useState<OrganizerTemplate[]>([]),[name,setName]=useState(''),[query,setQuery]=useState(''),[message,setMessage]=useState('');
  const [selected,setSelected]=useState(new Set<string>()),[managed,setManaged]=useState(''),[preview,setPreview]=useState<DrawerInterior|null>(null),[replacement,setReplacement]=useState<OrganizerTemplate|null>(null),[deleted,setDeleted]=useState<OrganizerTemplate|null>(null),[imports,setImports]=useState<OrganizerTemplate[]|null>(null),[skip,setSkip]=useState(new Set<string>()),[busy,setBusy]=useState(false);
  const field='border rounded p-2 w-full',current=templates.find(t=>t.id===managed),visible=templates.filter(t=>`${t.plan.name} ${(t.tags??[]).join(' ')} ${t.plan.cells.map(c=>c.category).join(' ')}`.toLowerCase().includes(query.trim().toLowerCase())&&(!compatible||(['width','depth','height'] as const).every(k=>Math.abs(innerSize(t.plan.source as DrawerTarget['drawer'],t.plan)[k]-innerSize(target.drawer,plan)[k])<=.125)));
  useEffect(()=>{const refresh=()=>{try{setTemplates(readTemplates(localStorage.getItem(TEMPLATE_KEY)));return true;}catch(e){setMessage((e as Error).message);return false;}};refresh();const external=(e:StorageEvent)=>{if(e.key===TEMPLATE_KEY||e.key===null){if(refresh())setMessage('Template library refreshed from another tab.');}};window.addEventListener('storage',external);return()=>window.removeEventListener('storage',external);},[]);
  const mutate=async(fn:(v:OrganizerTemplate[])=>OrganizerTemplate[],success:string,done?:()=>void)=>{setBusy(true);try{setTemplates(await mutateTemplates(fn));setRetry(null);setMessage(success);done?.();return true;}catch(e){setRetry({fn,success,done});setMessage(`Template change failed: ${(e as Error).message}`);return false;}finally{setBusy(false);}};
  return <fieldset disabled={busy} className="border p-2"><legend>My organizer templates</legend>
    <p>{20-templates.length} of 20 template spaces available. Replacement history retains five versions.</p>
    <label className="block"><input type="checkbox" checked={compatible} onChange={e=>setCompatible(e.target.checked)}/> Only templates matching current internal dimensions (within 0.125 in)</label>
    <button onClick={()=>{try{downloadText(localStorage.getItem(TEMPLATE_KEY)??'null','alveo-raw-templates.txt','text/plain');}catch(e){setMessage((e as Error).message);}}}>Download raw template recovery</button>
    {retry&&<button onClick={()=>mutate(retry.fn,retry.success,retry.done)}>Retry failed template change</button>}
    <label>Template name<input className={field} maxLength={80} value={name} onChange={e=>setName(e.target.value)}/></label><button disabled={!name.trim()} onClick={()=>mutate(fresh=>[...fresh,{id:crypto.randomUUID(),plan:{...structuredClone(plan),name:name.trim(),identity:undefined}}],'Template saved on this device.')}>Save custom template</button>
    <label className="block">Find templates<input className={field} value={query} onChange={e=>setQuery(e.target.value)}/></label>
    {visible.map(t=><label className="block" key={t.id}><input type="checkbox" checked={selected.has(t.id)} onChange={e=>setSelected(v=>{const next=new Set(v);e.target.checked?next.add(t.id):next.delete(t.id);return next;})}/> Export template {t.plan.name}</label>)}
    <button disabled={!templates.some(t=>selected.has(t.id))} onClick={()=>downloadText(serializeTemplates(templates.filter(t=>selected.has(t.id))),'alveo-organizer-templates.json')}>Download selected templates</button>
    <label className="block">Import organizer templates<input className="block w-full max-w-full" type="file" accept=".json,application/json" onChange={async e=>{const file=e.target.files?.[0];e.target.value='';setImports(null);if(!file)return;try{if(file.size>1024*1024)throw new Error('Template file exceeds 1 MB.');setImports(readTemplates(await file.text()));setSkip(new Set());setRenameImports({});}catch(error){setMessage((error as Error).message);}}}/></label>
    {imports&&<div><h3>Template import preview</h3><p>{imports.filter(t=>!skip.has(t.id)).length} selected; {20-templates.length} spaces remain.</p>{imports.map(t=><div key={t.id}><label className="block"><input type="checkbox" checked={!skip.has(t.id)} onChange={e=>setSkip(v=>{const next=new Set(v);e.target.checked?next.delete(t.id):next.add(t.id);return next;})}/> Keep {t.plan.name}{templates.some(v=>v.id===t.id||v.plan.name===t.plan.name)?' — conflict: imported copy gets a new ID':''}</label><label className="block">Imported name for {t.plan.name}<input className={field} maxLength={80} value={(Object.prototype.hasOwnProperty.call(renameImports,t.id)?renameImports[t.id]:t.plan.name)} onChange={e=>setRenameImports(v=>({...v,[t.id]:e.target.value}))}/></label></div>)}<button disabled={imports.filter(t=>!skip.has(t.id)).length+templates.length>20} onClick={async()=>{const copies=imports.filter(t=>!skip.has(t.id)).map(t=>({...t,id:crypto.randomUUID(),plan:{...t.plan,name:((Object.prototype.hasOwnProperty.call(renameImports,t.id)?renameImports[t.id]:t.plan.name)).trim()}}));await mutate(fresh=>[...fresh,...copies],'Templates imported.',()=>setImports(null));}}>Confirm template import</button><button onClick={()=>setImports(null)}>Cancel template import</button></div>}
    <label className="block">Preview custom template<select className={field} value="" onChange={e=>{const p=templates.find(t=>t.id===e.target.value)?.plan;if(p)setPreview({...structuredClone(p),measured:plan.measured,source:plan.source,identity:plan.identity});}}><option value="">Choose a template</option>{visible.map(t=><option value={t.id} key={t.id}>{t.plan.name}</option>)}</select></label>
    {preview&&<div><p>Scaled preview for this drawer: {innerSize(target.drawer,preview).width.toFixed(2)} × {innerSize(target.drawer,preview).depth.toFixed(2)} in.</p>{interiorWarnings(preview,target.drawer).map(w=><p role="status" key={w}>{w}</p>)}<div dangerouslySetInnerHTML={{__html:interiorSVG(preview,target.drawer)}}/><button onClick={()=>{change(preview);setPreview(null);}}>Apply template preview</button><button onClick={()=>setPreview(null)}>Cancel template preview</button></div>}
    <label className="block">Manage saved template<select className={field} value={managed} onChange={e=>{setManaged(e.target.value);setName(templates.find(t=>t.id===e.target.value)?.plan.name??'');setReplacement(null);setRevision('');setTags((templates.find(t=>t.id===e.target.value)?.tags??[]).join(', '));}}><option value="">Choose template to manage</option>{visible.map(t=><option value={t.id} key={t.id}>{t.plan.name}</option>)}</select></label>
    {current&&<div><label className="block">Template tags<input className={field} maxLength={490} value={tags} onChange={e=>setTags(e.target.value)}/></label><button onClick={()=>mutate(fresh=>fresh.map(t=>t.id===current.id?{...t,tags:Array.from(new Set(tags.split(',').map(v=>v.trim()).filter(Boolean))).slice(0,12).map(v=>v.slice(0,40))}:t),'Template tags saved.')}>Save template tags</button>
      <label className="block">Previous template version<select className={field} value={revision} onChange={e=>setRevision(e.target.value)}><option value="">Choose prior version</option>{current.revisions?.map(r=><option key={r.id} value={r.id}>{r.savedAt}</option>)}</select></label><button disabled={!revision} onClick={()=>{const id=crypto.randomUUID();void mutate(fresh=>{const r=fresh.find(t=>t.id===current.id)?.revisions?.find(v=>v.id===revision);if(!r)throw new Error('Template revision is no longer available.');return [...fresh,{id,plan:{...structuredClone(r.plan),name:r.plan.name.slice(0,65)+' (restored)'}}];},'Template version restored as a copy.');}}>Restore template version as copy</button><button disabled={!name.trim()} onClick={()=>mutate(fresh=>fresh.map(t=>t.id===current.id?{...t,plan:{...t.plan,name:name.trim()}}:t),'Template renamed.')}>Rename selected template</button><button onClick={async()=>{await mutate(fresh=>{const original=fresh.find(t=>t.id===current.id);if(!original||JSON.stringify(original)!==JSON.stringify(current))throw new Error('Template changed. Review it before deleting.');return fresh.filter(t=>t.id!==current.id);},'Template removed; undo is available.',()=>{setDeleted(current);setManaged('');});}}>Delete selected template</button><button onClick={()=>setReplacement(structuredClone(current))}>Preview template replacement</button></div>}
    {deleted&&<button onClick={async()=>{await mutate(fresh=>{if(fresh.some(t=>t.id===deleted.id))throw new Error('That template ID is already present.');return [...fresh,deleted];},'Template restored.',()=>setDeleted(null));}}>Undo template deletion</button>}
    {replacement&&<div><h3>Template replacement differences</h3><ul>{organizerChanges(replacement.plan,{...plan,name:replacement.plan.name}).map((text,i)=><li key={i}>{text}</li>)}</ul><button onClick={async()=>{const copy={...structuredClone(plan),name:replacement.plan.name,identity:undefined},revisionId=crypto.randomUUID(),savedAt=new Date().toISOString();await mutate(fresh=>{const original=fresh.find(t=>t.id===replacement.id);if(!original||JSON.stringify(original)!==JSON.stringify(replacement))throw new Error('Template changed since preview. Review it again.');return fresh.map(t=>t.id===replacement.id?{...t,plan:copy,revisions:[...(t.revisions??[]).slice(-4),{id:revisionId,savedAt,plan:structuredClone(t.plan)}]}:t);},'Template replaced.',()=>setReplacement(null));}}>Confirm template replacement</button><button onClick={()=>setReplacement(null)}>Cancel template replacement</button></div>}
    <button disabled={!templates.some(t=>selected.has(t.id))} onClick={()=>setBulk(structuredClone(templates.filter(t=>selected.has(t.id))))}>Preview deleting selected templates</button>
    {bulk&&<div><h3>Template deletion preview</h3><ul>{bulk.map(t=><li key={t.id}>{t.plan.name} — {t.id}</li>)}</ul><button onClick={async()=>{await mutate(fresh=>{for(const t of bulk)if(JSON.stringify(fresh.find(v=>v.id===t.id))!==JSON.stringify(t))throw new Error('A selected template changed; review the deletion again.');return fresh.filter(v=>!bulk.some(t=>t.id===v.id));},'Selected templates deleted.',()=>setBulk(null));}}>Delete previewed templates</button><button onClick={()=>setBulk(null)}>Cancel template deletion</button></div>}
    <p role="status">{message}</p>
  </fieldset>;
}
