'use client';
import { useEffect, useId, useRef, useState } from 'react';
import type { ClosetConfiguration, ClosetLayout, ClosetWall, PlanningOptions } from '@/types/closet';
import { WALL_IDS, MAX_DIMENSION, MAX_HEIGHT, MAX_CABINET_DEPTH } from '@/lib/planning';
import { circulation, doorAssessment, islandRequirement, obstacleSuggestions, roomIssues, roomSize, ceilingWarnings } from '@/lib/roomGeometry';
import { LIMITS, SHOE_SPACING } from '@/lib/design';
import { ClosetLayoutEngine } from '@/engine/ClosetLayoutEngine';
import { SettingsNavigation } from './SettingsNavigation';
import { RoomShells } from './RoomShells';

export function Measure({label,value,min=0,max=MAX_DIMENSION,onChange}:{label:string;value:number;min?:number;max?:number;onChange:(n:number)=>void}){
  const [raw,setRaw]=useState(String(value)),[error,setError]=useState(''),id=useId();
  useEffect(()=>{setRaw(String(value));setError('');},[value]);
  return <div><label htmlFor={id} className="text-sm block">{label}</label><input id={id} aria-invalid={!!error} aria-describedby={error?`${id}-error`:undefined} className="border rounded p-2 w-full" type="number" min={min} max={max} step={.125} value={raw} onChange={e=>setRaw(e.target.value)} onBlur={()=>{const n=Number(raw);if(!raw.trim()||!Number.isFinite(n)||n<min||n>max){setError(`Use ${min}–${max} inches.`);return;}setError('');onChange(n);}}/>{error&&<span id={`${id}-error`} role="alert">{error}</span>}</div>;
}
type WindowEntry=NonNullable<PlanningOptions['windows']>[number];
type Obstacle=NonNullable<PlanningOptions['obstacles']>[number];
export function PlanningControls({config,layout,onChange}:{config:Partial<ClosetConfiguration>;layout:ClosetLayout;onChange:(c:Partial<ClosetConfiguration>)=>void}){
  const settingsRoot=useRef<HTMLDetailsElement>(null);
  const p=config.planning??{},update=(patch:Partial<PlanningOptions>)=>onChange({planning:{...p,...patch}}),field='border rounded p-2 w-full';
  const [query,setQuery]=useState(''),[removed,setRemoved]=useState<{kind:'window';value:WindowEntry}|{kind:'obstacle';value:Obstacle}|null>(null);
  const [depthUndo,setDepthUndo]=useState<{wall:ClosetWall['wallId'];before:number|undefined;after:number}|null>(null),[floorPreview,setFloorPreview]=useState<{wall:ClosetWall['wallId'];offset:number}|null>(null);
  useEffect(()=>{const focus=(event:Event)=>{const id=(event as CustomEvent<string>).detail;setQuery('');requestAnimationFrame(()=>{const node=Array.from(document.querySelectorAll<HTMLElement>('[data-room-obstacle]')).find(el=>el.dataset.roomObstacle===id);let parent=node?.parentElement;while(parent){if(parent instanceof HTMLDetailsElement)parent.open=true;parent=parent.parentElement;}node?.querySelector('input')?.focus();node?.scrollIntoView({block:'center'});});};window.addEventListener('alveo-focus-obstacle',focus);return()=>window.removeEventListener('alveo-focus-obstacle',focus);},[]);
  const [depthPreview,setDepthPreview]=useState<{wall:ClosetWall['wallId'];depth:number}|null>(null);
  const issues=roomIssues(layout),door=doorAssessment(layout),room=roomSize(layout),aisles=circulation(layout),island=islandRequirement(layout);
  const preview=depthPreview?new ClosetLayoutEngine({...config,planning:{...p,walls:{...p.walls,[depthPreview.wall]:{...p.walls?.[depthPreview.wall],depth:depthPreview.depth}}}} as ClosetConfiguration).calculateLayout():null;
  const wallUpdate=(id:ClosetWall['wallId'],patch:NonNullable<PlanningOptions['walls']>[ClosetWall['wallId']])=>update({walls:{...p.walls,[id]:{...p.walls?.[id],...patch}}});
  const warnings=(kind:'window'|'obstacle',id:string)=><div className="text-sm text-red-800">{issues.filter(v=>v.kind===kind&&v.id===id).map((v,i)=><p role="status" key={i}>{v.message}</p>)}</div>;
  const matches=(s:string)=>s.toLocaleLowerCase().includes(query.trim().toLocaleLowerCase());
  return <details id="studio-room-tools" ref={settingsRoot} className="room-settings border rounded p-3 mt-3"><summary>Room openings, wall preferences, and sizing assumptions</summary><SettingsNavigation root={settingsRoot} label="Room settings sections" items={[['assumptions','Fit assumptions'],['walls','Walls'],['door','Door'],['windows','Windows'],['obstacles','Obstacles']]}/>
    <p className="text-xs my-2">All measurements are inches. Room limit: {MAX_DIMENSION} × {MAX_DIMENSION}; ceiling: {MAX_HEIGHT}. Window spans reserve whole cabinet columns. Door checks are geometric planning estimates.</p>
    <section data-settings-section="assumptions" className="settings-card"><h3>Fit assumptions</h3><p className="settings-description">Default clearances used to allocate your storage.</p><div className="grid grid-cols-2 gap-2"><Measure label="Long garment length" min={24} max={100} value={p.garmentLengths?.long??60} onChange={long=>update({garmentLengths:{long,short:p.garmentLengths?.short??30}})}/><Measure label="Short garment length" min={12} max={60} value={p.garmentLengths?.short??30} onChange={short=>update({garmentLengths:{short,long:p.garmentLengths?.long??60}})}/>{Object.entries(SHOE_SPACING).map(([k,v])=><Measure key={k} label={`${k} shoe clearance`} min={2} max={36} value={p.shoeHeights?.[k as 'boots']??v} onChange={n=>update({shoeHeights:{...SHOE_SPACING,...p.shoeHeights,[k]:n}})}/>)}<Measure label="Minimum accessory shelf opening" min={8} max={36} value={p.accessoryShelfOpening??14} onChange={accessoryShelfOpening=>update({accessoryShelfOpening})}/><Measure label="Maximum unsupported shelf span" min={12} max={48} value={p.supportSpan??32} onChange={supportSpan=>update({supportSpan})}/><Measure label="Personal aisle clearance target" min={18} max={72} value={p.clearanceTarget??36} onChange={clearanceTarget=>update({clearanceTarget})}/></div>
    <label className="flex items-start gap-2 my-3"><input type="checkbox" className="mt-1" checked={p.upperStorage!==false} onChange={e=>update({upperStorage:e.target.checked})}/><span>Use spare upper space for shelves<span className="block text-xs text-gray-600">Adds seasonal storage above rods and shoe openings when the minimum shelf opening fits. Turn off to leave those spaces open.</span></span></label>
    <p className="text-xs">The personal target is not a building-code assessment. Narrowest modeled storage aisle: {aisles.narrowest.name}, {aisles.narrowest.width.toFixed(2)} in. Room obstacles and door conflicts are checked separately.</p>
    {layout.closetType==='island'&&!layout.walls.some(w=>w.wallId==='island-unit')&&<p role="status">Island omitted. A 36-inch island needs a room at least {island.width} × {island.depth} in for the {island.target}-inch target and current cabinet depths.</p>}
    </section><fieldset data-settings-section="walls" className="settings-card"><legend>Per-wall preferences</legend>{layout.walls.map(w=><div key={w.wallId} className="settings-object-card"><h4>{w.label}</h4>
      <Measure label={`${w.label} cabinet depth`} min={LIMITS.depthMin} max={MAX_CABINET_DEPTH} value={p.walls?.[w.wallId]?.depth??config.dimensions?.depth??24} onChange={depth=>setDepthPreview({wall:w.wallId,depth})}/>
      <label className="text-sm">{w.label} priority<select className={field} value={p.walls?.[w.wallId]?.priority??'default'} disabled={w.wallId==='island-unit'} onChange={e=>wallUpdate(w.wallId,{priority:e.target.value as 'default'})}>{['default','hanging','shoes','folded','accessories'].map(v=><option key={v}>{v}</option>)}</select></label>
      {w.wallId!=='island-unit'&&<><Measure label={`${w.label} measured ceiling height`} min={LIMITS.height} max={MAX_HEIGHT} value={p.walls?.[w.wallId]?.ceilingHeight??layout.dimensions.height} onChange={ceilingHeight=>wallUpdate(w.wallId,{ceilingHeight})}/><p className="text-xs">Measured wall ceiling constrains generated cabinet height. Floor offsets reduce the usable height below that ceiling.</p><Measure label={`${w.label} baseboard allowance`} max={6} value={p.walls?.[w.wallId]?.baseboard??0} onChange={baseboard=>wallUpdate(w.wallId,{baseboard})}/><p className="text-xs">Usable cabinet depth: {(w.unitDepth-(p.walls?.[w.wallId]?.baseboard??0)).toFixed(2)} in.</p><Measure label={`${w.label} floor offset`} max={12} value={p.walls?.[w.wallId]?.floorOffset??0} onChange={offset=>setFloorPreview({wall:w.wallId,offset})}/></>}
    </div>)}</fieldset>
    {depthPreview&&preview&&<div className="border rounded p-3" role="region" aria-label="Cabinet depth preview"><h3>Cabinet depth preview</h3><p>{depthPreview.wall}: {depthPreview.depth} in. Shelf area change: {(preview.totalStorage.shelfSpace-layout.totalStorage.shelfSpace).toFixed(2)} sq ft; drawer count change: {preview.totalStorage.drawerCount-layout.totalStorage.drawerCount}.</p>{preview.capacity?.map(c=><p className="text-sm" key={c.label}>{c.label}: {(layout.capacity?.find(v=>v.label===c.label)?.available??0).toFixed(2)} → {c.available.toFixed(2)} {c.unit}; unmet {Math.max(0,c.required-c.available).toFixed(2)}.</p>)}<p>Narrowest aisle: {circulation(preview).narrowest.width.toFixed(2)} in.</p><button onClick={()=>{setDepthUndo({wall:depthPreview.wall,before:p.walls?.[depthPreview.wall]?.depth,after:depthPreview.depth});wallUpdate(depthPreview.wall,{depth:depthPreview.depth});setDepthPreview(null);}}>Apply cabinet depth</button><button onClick={()=>setDepthPreview(null)}>Cancel depth change</button></div>}
    {depthUndo&&<button disabled={p.walls?.[depthUndo.wall]?.depth!==depthUndo.after} onClick={()=>{wallUpdate(depthUndo.wall,{depth:depthUndo.before});setDepthUndo(null);}}>Undo cabinet depth change</button>}
    {floorPreview&&<div><h3>Floor offset preview</h3><p>{floorPreview.wall}: usable storage height {(layout.dimensions.height-(p.walls?.[floorPreview.wall]?.floorOffset??0)).toFixed(2)} → {(layout.dimensions.height-floorPreview.offset).toFixed(2)} in; lower edge raised to {floorPreview.offset} in.</p><button onClick={()=>{wallUpdate(floorPreview.wall,{floorOffset:floorPreview.offset});setFloorPreview(null);}}>Apply floor offset</button><button onClick={()=>setFloorPreview(null)}>Cancel floor offset</button></div>}
    {ceilingWarnings(layout).map(w=><p role="status" key={w}>{w}</p>)}
    <section data-settings-section="door" className="settings-card"><h3>Door opening</h3><p className="settings-description">Set the door location and swing to review conflicts with storage.</p><label className="block"><input type="checkbox" checked={!!p.door} onChange={e=>update({door:e.target.checked?{wall:'front',offset:0,width:30,hinge:'left',swing:'in'}:undefined})}/> Use measured door opening</label>
    {p.door&&<div className="grid grid-cols-2 gap-2 my-2"><label>Door wall<select className={field} value={p.door.wall} onChange={e=>update({door:{...p.door!,wall:e.target.value as 'front'}})}>{['front','back','left','right'].map(v=><option key={v}>{v}</option>)}</select></label><Measure label="Door width" value={p.door.width} min={18} max={72} onChange={width=>update({door:{...p.door!,width}})}/><Measure label="Door offset along wall" value={p.door.offset} onChange={offset=>update({door:{...p.door!,offset}})}/><label>Door hinge<select className={field} value={p.door.hinge} onChange={e=>update({door:{...p.door!,hinge:e.target.value as 'left'}})}><option>left</option><option>right</option></select></label><label>Door swing<select className={field} value={p.door.swing} onChange={e=>update({door:{...p.door!,swing:e.target.value as 'in'}})}><option>in</option><option>out</option></select></label><label>Door clearance model<select className={field} value={p.door.check??'envelope'} onChange={e=>update({door:{...p.door!,check:e.target.value as 'sector'}})}><option value="envelope">Conservative square envelope</option><option value="sector">Swept quarter-circle sector</option></select></label><p className="text-xs col-span-2">Offsets start at front-left, left-back, back-right, or right-front corner. Door-to-storage minimum clearance: {door.clearance===null?'no storage':`${door.clearance.toFixed(2)} in`}. Door-to-obstacle minimum clearance: {door.obstacleClearance===null?'no obstacles':`${door.obstacleClearance.toFixed(2)} in`}. Smallest checked door pair: {door.closestPair??'none'}. {door.conflicts.length?`Conflicts: ${door.conflicts.join(', ')}.`:'No modeled intersections.'} {door.outside?'Door extends beyond wall.':''}</p></div>}
    </section>
    <div className="settings-object-search"><label className="block">Find room objects<input className={field} value={query} onChange={e=>setQuery(e.target.value)} placeholder="Window or obstacle name"/></label>{query&&<button type="button" onClick={()=>setQuery('')}>Clear room search</button>}<p role="status" className="settings-description">{(p.windows??[]).filter((w,i)=>matches(`Window ${i+1} ${w.label??''}`)).length} windows · {(p.obstacles??[]).filter((o,i)=>matches(`Obstacle ${i+1} ${o.label}`)).length} obstacles{query?' match your search':' in this room'}</p></div>
    {removed&&<button onClick={()=>{if(removed.kind==='window'){if((p.windows?.length??0)>=20)return;update({windows:[...p.windows??[],removed.value]});}else{if((p.obstacles?.length??0)>=20)return;update({obstacles:[...p.obstacles??[],removed.value]});}setRemoved(null);}}>Undo room object removal</button>}
    <fieldset data-settings-section="windows" className="settings-card"><legend>Windows</legend><p className="settings-description">Place openings along a wall to reserve space in your layout.</p>{!p.windows?.length?<p className="settings-empty">No windows added. Add an opening if this room has a window.</p>:!p.windows.some((w,i)=>matches(`Window ${i+1} ${w.label??''}`))&&<p className="settings-empty">No windows match your search.</p>}{p.windows?.map((w,i)=>matches(`Window ${i+1} ${w.label??''}`)&&<div className="settings-object-card" key={w.id}><h4>Window {i+1}{w.label?` · ${w.label}`:''}</h4><label>Window {i+1} name<input className={field} maxLength={80} value={w.label??''} onChange={e=>update({windows:p.windows!.map(v=>v.id===w.id?{...v,label:e.target.value}:v)})}/></label><label>Window wall<select className={field} value={w.wall} onChange={e=>update({windows:p.windows!.map(v=>v.id===w.id?{...v,wall:e.target.value as typeof w.wall}:v)})}>{WALL_IDS.filter(v=>v!=='island-unit').map(v=><option key={v}>{v}</option>)}</select></label><div className="grid grid-cols-2 gap-2">{(['offset','width','sill','height'] as const).map(k=><Measure key={k} label={`Window ${i+1} ${k}`} min={k==='width'||k==='height'?1:0} max={k==='sill'||k==='height'?MAX_HEIGHT:MAX_DIMENSION} value={w[k]} onChange={n=>update({windows:p.windows!.map(v=>v.id===w.id?{...v,[k]:n}:v)})}/>)}</div>{warnings('window',w.id)}<button disabled={p.windows!.length>=20} onClick={()=>update({windows:[...p.windows!,{...w,id:crypto.randomUUID(),label:`${w.label??'Window'} copy`.slice(0,80)}]})}>Duplicate window {i+1}</button><button onClick={()=>{setRemoved({kind:'window',value:w});update({windows:p.windows!.filter(v=>v.id!==w.id)});}}>Remove window {i+1}</button></div>)}<button disabled={(p.windows?.length??0)>=20} onClick={()=>{setQuery('');update({windows:[...p.windows??[],{id:crypto.randomUUID(),wall:layout.walls.find(w=>w.wallId!=='island-unit')?.wallId??'back',offset:0,width:24,sill:36,height:36}]});}}>Add window</button></fieldset>
    <fieldset data-settings-section="obstacles" className="settings-card"><legend>Columns and obstacles</legend><p className="settings-description">Reserve the footprint of columns and other fixed objects.</p>{!p.obstacles?.length?<p className="settings-empty">No obstacles added. Add any fixed object that storage needs to avoid.</p>:!p.obstacles.some((o,i)=>matches(`Obstacle ${i+1} ${o.label}`))&&<p className="settings-empty">No obstacles match your search.</p>}{p.obstacles?.map((o,i)=>matches(`Obstacle ${i+1} ${o.label}`)&&<div className="settings-object-card" key={o.id} data-room-obstacle={o.id}><h4>Obstacle {i+1} · {o.label}</h4><label>Obstacle {i+1} label<input className={field} maxLength={80} value={o.label} onChange={e=>update({obstacles:p.obstacles!.map(v=>v.id===o.id?{...v,label:e.target.value}:v)})}/></label><div className="grid grid-cols-2 gap-2">{(['x','y','width','depth'] as const).map(k=><Measure key={k} label={`Obstacle ${i+1} ${k}`} min={k==='width'||k==='depth'?1:0} value={o[k]} onChange={n=>update({obstacles:p.obstacles!.map(v=>v.id===o.id?{...v,[k]:n}:v)})}/>)}<Measure label={`Obstacle ${i+1} distance from right wall`} max={Math.max(0,room.width-o.width)} value={room.width-o.x-o.width} onChange={n=>update({obstacles:p.obstacles!.map(v=>v.id===o.id?{...v,x:room.width-o.width-n}:v)})}/><Measure label={`Obstacle ${i+1} distance from front wall`} max={Math.max(0,room.depth-o.depth)} value={room.depth-o.y-o.depth} onChange={n=>update({obstacles:p.obstacles!.map(v=>v.id===o.id?{...v,y:room.depth-o.depth-n}:v)})}/></div>{warnings('obstacle',o.id)}{obstacleSuggestions(layout,o.id).map(pos=><button className="block" key={`${pos.x},${pos.y}`} onClick={()=>update({obstacles:p.obstacles!.map(v=>v.id===o.id?{...v,...pos}:v)})}>Move {o.label} to clear position {pos.x.toFixed(2)}, {pos.y.toFixed(2)} in</button>)}<button disabled={p.obstacles!.length>=20} onClick={()=>update({obstacles:[...p.obstacles!,{...o,id:crypto.randomUUID(),label:`${o.label} copy`.slice(0,80)}]})}>Duplicate obstacle {i+1}</button><button onClick={()=>{setRemoved({kind:'obstacle',value:o});update({obstacles:p.obstacles!.filter(v=>v.id!==o.id)});}}>Remove obstacle {i+1}</button></div>)}<button disabled={(p.obstacles?.length??0)>=20} onClick={()=>{setQuery('');update({obstacles:[...p.obstacles??[],{id:crypto.randomUUID(),label:'Column',x:0,y:0,width:12,depth:12}]});}}>Add obstacle</button><p className="text-xs">X is from the left wall; Y is from the back wall.</p></fieldset>
    <RoomShells config={config} onChange={onChange}/>
  </details>;
}

