'use client';
import { useState } from 'react';
import { DEFAULT_PRINT, storedPrintSettings } from '@/lib/printSettings';
import type { PrintSettings } from '@/lib/printSettings';
const KEY='alveo-print-presets';
export function PrintPresets({settings,onApply}:{settings:PrintSettings;onApply:(s:PrintSettings)=>void}){
 const [name,setName]=useState(''),[message,setMessage]=useState(''),[rename,setRename]=useState('');
 const read=():Record<string,PrintSettings>=>{const raw=localStorage.getItem(KEY);if(!raw)return {};const value=JSON.parse(raw);if(value?.version!==1||!Array.isArray(value.presets)||value.presets.length>20)throw new Error('Print preset storage is unreadable.');const result:Record<string,PrintSettings>=Object.create(null);for(const p of value.presets){if(typeof p?.name!=='string'||!p.name.trim()||p.name.length>80||Object.prototype.hasOwnProperty.call(result,p.name))throw new Error('Invalid print preset name.');result[p.name]=storedPrintSettings(JSON.stringify(p.settings));}return result;};
 const action=(kind:'save'|'load'|'delete'|'rename')=>{try{const title=name.trim();if(!title)throw new Error('Enter a preset name.');const presets=read();if(kind==='load'){if(!Object.prototype.hasOwnProperty.call(presets,title))throw new Error('No preset with that name.');onApply(presets[title]);}else{if(kind==='save'){if(!Object.prototype.hasOwnProperty.call(presets,title)&&Object.keys(presets).length>=20)throw new Error('Maximum 20 print presets.');presets[title]=storedPrintSettings(JSON.stringify(settings));}else if(kind==='rename'){const next=rename.trim();if(!Object.prototype.hasOwnProperty.call(presets,title))throw new Error('No preset with that name.');if(!next)throw new Error('Enter the new preset name.');if(next!==title&&Object.prototype.hasOwnProperty.call(presets,next))throw new Error('That preset name already exists.');presets[next]=presets[title];if(next!==title)delete presets[title];}else delete presets[title];localStorage.setItem(KEY,JSON.stringify({version:1,presets:Object.entries(presets).map(([name,settings])=>({name,settings}))}));if(kind==='rename')setName(rename.trim());}setMessage(kind==='load'?'Preset applied.':kind==='save'?'Preset saved.':kind==='rename'?'Preset renamed.':'Preset removed.');}catch(e){setMessage(e instanceof Error?e.message:'Print preset operation failed.');}};
 return <details><summary>Named print presets</summary><p>Save paper, section, project and contact preferences. Wall selections and comparison references are specific to each design.</p><label>Print preset name<input className="border p-2 w-full" maxLength={80} value={name} onChange={e=>setName(e.target.value)}/></label><label>New print preset name<input className="border p-2 w-full" maxLength={80} value={rename} onChange={e=>setRename(e.target.value)}/></label><div className="flex flex-wrap gap-3"><button onClick={()=>action('rename')}>Rename print preset</button><button onClick={()=>action('save')}>Save print preset</button><button onClick={()=>action('load')}>Load print preset</button><button onClick={()=>action('delete')}>Delete print preset</button><button onClick={()=>{onApply({...DEFAULT_PRINT});setMessage('Print preferences reset to defaults.');}}>Reset print preferences</button><button onClick={()=>{try{setMessage('Saved presets: '+(Object.keys(read()).join(', ')||'none'));}catch(e){setMessage(String(e));}}}>List print presets</button></div><p role="status">{message}</p></details>;
}
