'use client';
import { useEffect, useState } from 'react';
import type { ClosetConfiguration } from '@/types/closet';
import { mutateShells, readShells, roomShell, ROOM_SHELL_KEY, serializeShells, shellMeasurements } from '@/lib/roomShells';
import type { SavedShell, Shell } from '@/lib/roomShells';
import { downloadText } from '@/lib/download';
export { roomShell } from '@/lib/roomShells';
export function RoomShells({config,onChange}:{config:Partial<ClosetConfiguration>;onChange:(patch:Partial<ClosetConfiguration>)=>void}){
  const [saved,setSaved]=useState<SavedShell[]>([]),[name,setName]=useState(''),[preview,setPreview]=useState<SavedShell|null>(null),[message,setMessage]=useState('');
  const [query,setQuery]=useState(''),[managed,setManaged]=useState(''),[selected,setSelected]=useState(new Set<string>()),[deleted,setDeleted]=useState<SavedShell|null>(null),[busy,setBusy]=useState(false);
  const [incoming,setIncoming]=useState<SavedShell[]|null>(null),[skip,setSkip]=useState(new Set<string>()),[undo,setUndo]=useState<{before:Shell;after:Shell}|null>(null);
  useEffect(()=>{const refresh=()=>{try{setSaved(readShells(localStorage.getItem(ROOM_SHELL_KEY)));}catch(e){setMessage((e as Error).message);}};refresh();const external=(e:StorageEvent)=>{if(e.key===ROOM_SHELL_KEY||e.key===null)refresh();};window.addEventListener('storage',external);return()=>window.removeEventListener('storage',external);},[]);
  const change=async(fn:(current:SavedShell[])=>SavedShell[],success:string)=>{setBusy(true);try{setSaved(await mutateShells(fn));setMessage(success);return true;}catch(e){setMessage((e as Error).message);return false;}finally{setBusy(false);}};
  const current=roomShell(config),visible=saved.filter(v=>`${v.name} ${v.shell.closetType}`.toLowerCase().includes(query.toLowerCase())),one=saved.find(v=>v.id===managed),a=shellMeasurements(current),b=preview?shellMeasurements(preview.shell):new Map<string,string>(),rows=Array.from(new Set([...a.keys(),...b.keys()])),field='border rounded p-2 w-full';
  const unchanged=(fresh:SavedShell[])=>{if(!one||JSON.stringify(fresh.find(v=>v.id===one.id))!==JSON.stringify(one))throw new Error('Room shell changed in another tab. Review it again.');};
  return <details className="border rounded p-3 my-3"><summary>Reusable room shells</summary><fieldset disabled={busy} className="min-w-0">
    <p className="text-sm">Save room measurements and openings separately from wardrobe inventory and drawer organizers. {20-saved.length} of 20 shell spaces remain on this device.</p>
    <label className="block">Room shell name<input className={field} maxLength={80} value={name} onChange={e=>setName(e.target.value)}/></label>
    <button disabled={!name.trim()} onClick={()=>{const id=crypto.randomUUID();void change(fresh=>[...fresh,{id,name:name.trim(),shell:current}],'Room shell saved.');}}>Save room shell</button>
    <label className="block">Search room shells<input className={field} value={query} onChange={e=>setQuery(e.target.value)}/></label>
    <label className="block">Manage room shell<select className={field} value={managed} onChange={e=>{setManaged(e.target.value);setName(saved.find(v=>v.id===e.target.value)?.name??'');}}><option value="">Choose shell</option>{visible.map(v=><option key={v.id} value={v.id}>{v.name}</option>)}</select></label>
    {one&&<div className="flex flex-wrap gap-2"><button disabled={!name.trim()} onClick={()=>change(fresh=>{unchanged(fresh);return fresh.map(v=>v.id===one.id?{...v,name:name.trim()}:v);},'Room shell renamed.')}>Rename room shell</button><button disabled={!name.trim()} onClick={()=>{const id=crypto.randomUUID();void change(fresh=>{unchanged(fresh);return [...fresh,{...structuredClone(one),id,name:name.trim()}];},'Independent room shell copied.');}}>Duplicate room shell</button><button onClick={async()=>{if(await change(fresh=>{unchanged(fresh);return fresh.filter(v=>v.id!==one.id);},'Room shell deleted. Undo is available.')){setDeleted(one);setManaged('');}}}>Delete room shell</button></div>}
    {deleted&&<button onClick={async()=>{if(await change(fresh=>{if(fresh.some(v=>v.id===deleted.id))throw new Error('Shell ID already exists.');return [...fresh,deleted];},'Room shell restored.'))setDeleted(null);}}>Undo shell deletion</button>}
    {visible.map(v=><label className="block" key={v.id}><input type="checkbox" checked={selected.has(v.id)} onChange={e=>setSelected(old=>{const next=new Set(old);e.target.checked?next.add(v.id):next.delete(v.id);return next;})}/> Export shell {v.name}</label>)}
    <button disabled={!saved.some(v=>selected.has(v.id))} onClick={()=>downloadText(serializeShells(saved.filter(v=>selected.has(v.id))),'alveo-room-shells.json')}>Download selected room shells</button>
    <label className="block">Import room shells<input className="block w-full max-w-full" type="file" accept=".json,application/json" onChange={async e=>{const file=e.target.files?.[0];e.target.value='';setIncoming(null);if(!file)return;try{if(file.size>1024*1024)throw new Error('Room-shell file exceeds 1 MB.');setIncoming(readShells(await file.text()));setSkip(new Set());}catch(error){setMessage((error as Error).message);}}}/></label>
    {incoming&&<div><h3>Room-shell import preview</h3>{incoming.map(v=><label key={v.id} className="block"><input type="checkbox" checked={!skip.has(v.id)} onChange={e=>setSkip(old=>{const next=new Set(old);e.target.checked?next.delete(v.id):next.add(v.id);return next;})}/> Keep {v.name}{saved.some(s=>s.id===v.id||s.name===v.name)?' — conflict: keep as an independent copy':''}</label>)}<button disabled={!incoming.some(v=>!skip.has(v.id))} onClick={async()=>{const copies=incoming.filter(v=>!skip.has(v.id)).map(v=>({...v,id:crypto.randomUUID()}));if(await change(fresh=>[...fresh,...copies],'Room shells imported.'))setIncoming(null);}}>Import selected room shells</button><button onClick={()=>setIncoming(null)}>Cancel shell import</button></div>}
    <label className="block">Compare saved room shell<select className={field} value={preview?.id??''} onChange={e=>setPreview(saved.find(v=>v.id===e.target.value)??null)}><option value="">Choose a shell</option>{visible.map(v=><option value={v.id} key={v.id}>{v.name}</option>)}</select></label>
    {preview&&<div><h3>Room shell comparison</h3><div className="overflow-auto"><table className="w-full text-sm"><thead><tr><th>Measurement</th><th>Current</th><th>{preview.name}</th></tr></thead><tbody>{rows.map(key=><tr key={key}><th className="break-words">{key}</th><td>{a.get(key)??'None'}</td><td>{b.get(key)??'None'}</td></tr>)}</tbody></table></div><p>Replacing the room may resize or retain existing organizers for reassignment. Inventory quantities stay the same.</p><button onClick={()=>{const after=structuredClone(preview.shell);setUndo({before:current,after});onChange(after);setPreview(null);setMessage('Room shell applied. Review retained organizers and clearances.');}}>Apply compared room shell</button><button onClick={()=>setPreview(null)}>Cancel room shell comparison</button></div>}
    {undo&&<button onClick={()=>{if(JSON.stringify(current)!==JSON.stringify(undo.after)){setMessage('Room measurements changed since applying the shell. Undo would overwrite those edits.');return;}onChange(structuredClone(undo.before));setUndo(null);setMessage('Previous room restored.');}}>Undo applied room shell</button>}
    <p role="status">{message}</p></fieldset></details>;
}
